Handover with consensus integration (squashed)
maidsafe/safe_network pull request #1131
Opened 2022-04-22 15:09 UTC by grumbach

- Add a consensus step between SectionInfo agreement and triggering NewElders
- Consensus serves as a race-condition guard to avoid concurrent handovers/agreements
- Add a DKG retry mechanism on timeouts

2022-04-22 15:13 UTC, grumbach commented on sn_interface/src/network_knowledge/section_authority_provider.rs
> +
Need help on this

2022-04-22 15:15 UTC, grumbach commented on sn_node/src/node/core/messaging/handling/agreement.rs
> +        let chosen_candidates = self.split_barrier.write().await.process(
Split barrier is not yet equipped with membership generations information, so 2 split SAPs from different gens could theoretically go in, will need to prevent cross generation race conditions in a follow up PR.

2022-04-22 15:18 UTC, grumbach commented on sn_node/src/node/core/mod.rs
> +                    // NB TODO non-elders should clear their handover_voting field and put None
```suggestion

```

2022-04-25 10:12 UTC, joshuef commented
We've some maaaad logging going on atm. eg ```handle_handover_msg {signed_vote=G0-SM{G0-M{G0-P(SectionSplit(SectionAuth { value: SectionAuthorityProvider { prefix: Prefix(0), public_key_set: PublicKeySet { public_key: PublicKey(1305..e4f6), threshold: 4 }, elders: {Peer { name: 0d6cdc(00001101).., addr: 127.0.0.1:49651 }, Peer { name: 0fb154(00001111).., addr: 127.0.0.1:54135 }, Peer { name: 272062(00100111).., addr: 127.0.0.1:60915 }, Peer { name: 354179(00110101).., addr: 127.0.0.1:58321 }, Peer { name: 4672aa(01000110).., addr: 127.0.0.1:51618 }, Peer { name: 67a325(01100111).., addr: 127.0.0.1:60539 }, Peer { name: 77c226(01110111).., addr: 127.0.0.1:50472 }}, members: {NodeState { peer: Peer { name: 075355(00000111).., addr: 127.0.0.1:52400 }, state: Joined, previous_name: None }, NodeState { peer: Peer { name: 0d6cdc(00001101).., addr: 127.0.0.1:49651 }, state: Joined, previous_name: None }, NodeState { peer: Peer { name: 0fb154(00001111).., addr: 127.0.0.1:54135 }, state: Joined, previous_name: None }, NodeState { peer: Peer { name: 1b41b5(00011011).., addr: 127.0.0.1:52267 }, state: Joined, previous_name: None }, NodeState { peer: Peer { name: 272062(00100111).., addr: 127.0.0.1:60915 }, state: Joined, previous_name: None }, NodeState { peer: Peer { name: 283c37(00101000).., addr: 127.0.0.1:62958 }, state: Joined, previous_name: None }, NodeState { peer: Peer { name: 354179(00110101).., addr: 127.0.0.1:58321 }, state: Joined, previous_name: None }, NodeState { peer: Peer { name: 3c06ec(00111100).., addr: 127.0.0.1:61554 }, state: Joined, previous_name: None }, NodeState { peer: Peer { name: 4672aa(01000110).., addr: 127.0.0.1:51618 }, state: Joined, previous_name: None }, NodeState { peer: Peer { name: 4e4af4(01001110).., addr: 127.0.0.1:64870 }, state: Joined, previous_name: None }, NodeState { peer: Peer { name: 5dedad(01011101).., addr: 127.0.0.1:50555 }, state: Joined, previous_name: None }, NodeState { peer: Peer { name: 67a325(01100111).., addr: 127.0.0.1:60539 }, state: Joined, previous_name: None }, NodeState { peer: Peer { name: 6a9f44(01101010).., addr: 127.0.0.1:51622 }, state: Joined, previous_name: None }, NodeState { peer: Peer { name: 77c226(01110111).., addr: 127.0.0.1:50472 }, state: Joined, previous_name: None }, NodeState { peer: Peer { name: 7967ef(01111001).., addr: 127.0.0.1:63253 }, state: Joined, previous_name: None }} }, sig: KeyedSig { public_key: PublicKey(1305..e4f6), signature: Signature(0f15..b973) } }, SectionAuth { value: SectionAuthorityProvider { prefix: Prefix(1), public_key_set: PublicKeySet { public_key: PublicKey(051c..aef2), threshold: 4 }, elders: {Peer { name: 87cbc4(10000111).., addr: 127.0.0.1:56328 }, Peer { name: 8d38d7(10001101).., addr: 127.0.0.1:50892 }, Peer { name: a7b544(10100111).., addr: 127.0.0.1:57750 }, Peer { name: b56a42(10110101).., addr: 127.0.0.1:56090 }, Peer { name: c65e07(11000110).., addr: 127.0.0.1:55890 }, Peer { name: f7479d(11110111).., addr: 127.0.0.1:60084 }, Peer { name: f9d120(11111001).., addr: 127.0.0.1:62572 }}, members: {NodeState { peer: Peer { name: 87cbc4(10000111).., addr: 127.0.0.1:56328 }, state: Joined, previous_name: None }, NodeState { peer: Peer { name: 89aac8(10001001).., addr: 127.0.0.1:53284 }, state: Joined, previous_name: None }, NodeState { peer: Peer { name: 8d38d7(10001101).., addr: 127.0.0.1:50892 }, state: Joined, previous_name: None }, NodeState { peer: Peer { name: 9ef3c9(10011110).., addr: 127.0.0.1:61930 }, state: Joined, previous_name: None }, NodeState { peer: Peer { name: a7b544(10100111).., addr: 127.0.0.1:57750 }, state: Joined, previous_name: None }, NodeState { peer: Peer { name: ae6eda(10101110).., addr: 127.0.0.1:56691 }, state: Joined, previous_name: None }, NodeState { peer: Peer { name: b56a42(10110101).., addr: 127.0.0.1:56090 }, state: Joined, previous_name: None }, NodeState { peer: Peer { name: b89be3(10111000).., addr: 127.0.0.1:50141 }, state: Joined, previous_name: None }, NodeState { peer: Peer { name: c65e07(11000110).., addr: 127.0.0.1:55890 }, state: Joined, previous_name: None }, NodeState { peer: Peer { name: ce846f(11001110).., addr: 127.0.0.1:53031 }, state: Joined, previous_name: None }, NodeState { peer: Peer { name: db60c2(11011011).., addr: 127.0.0.1:62747 }, state: Joined, previous_name: None }, NodeState { peer: Peer { name: eced32(11101100).., addr: 127.0.0.1:58958 }, state: Joined, previous_name: None }, NodeState { peer: Peer { name: f7479d(11110111).., addr: 127.0.0.1:60084 }, state: Joined, previous_name: None }, NodeState { peer: Peer { name: f9d120(11111001).., addr: 127.0.0.1:62572 }, state: Joined, previous_name: None }} }, sig: KeyedSig { public_key: PublicKey(051c..aef2), signature: Signature(0d6c..4fa1) } }))@1, G0-P(SectionSplit(SectionAuth { value: SectionAuthorityProvider { prefix: Prefix(0), public_key_set: PublicKeySet { public_key: PublicKey(1305..e4f6), threshold: 4 }, elders: {Peer { name: 0d6cdc(00001101).., addr: 127.0.0.1:49651 }, Peer { name: 0fb154(00001111).., addr: 127.0.0.1:54135 }, Peer { name: 272062(00100111).., addr: 127.0.0.1:60915 }, Peer { name: 354179(00110101).., addr: 127.0.0.1:58321 }, Peer { name: 4672aa(01000110).., addr: 127.0.0.1:51618 }, Peer { name: 67a325(01100111).., addr: 127.0.0.1:60539 }, Peer { name: 77c226(01110111).., addr: 127.0.0.1:50472 }}, members: {NodeState { peer: Peer { name: 075355(00000111).., addr: 127.0.0.1:52400 }, state: Joined, previous_name: None }, NodeState { peer: Peer { name: 0d6cdc(00001101).., addr: 127.0.0.1:49651 }, state: Joined, previous_name: None }, NodeState { peer: Peer { name: 0fb154(00001111).., addr: 127.0.0.1:54135 }, state: Joined, previous_name: None }, NodeState { peer: Peer { name: 1b41b5(00011011).., addr: 127.0.0.1:52267 }, state: Joined, previous_name: None }, NodeState { peer: Peer { name: 272062(00100111).., addr: 127.0.0.1:60915 }, state: Joined, previous_name: None }, NodeState { peer: Peer { name: 283c37(00101000).., addr: 127.0.0.1:62958 }, state: Joined, previous_name: None }, NodeState { peer: Peer { name: 354179(00110101).., addr: 127.0.0.1:58321 }, state: Joined, previous_name: None }, NodeState { peer: Peer { name: 3c06ec(00111100).., addr: 127.0.0.1:61554 }, state: Joined, previous_name: None }, NodeState { peer: Peer { name: 4672aa(01000110).., addr: 127.0.0.1:51618 }, state: Joined, previous_name: None }, NodeState { peer: Peer { name: 4e4af4(01001110).., addr: 127.0.0.1:64870 }, state: Joined, previous_name: None }, NodeState { peer: Peer { name: 5dedad(01011101).., addr: 127.0.0.1:50555 }, state: Joined, previous_name: None }, NodeState { peer: Peer { name: 67a325(01100111).., addr: 127.0.0.1:60539 }, state: Joined, previous_name: None }, NodeState { peer: Peer { name: 6a9f44(01101010).., ```

2022-04-25 14:38 UTC, joshuef requested changes

2022-04-25 14:38 UTC, joshuef commented on sn_node/src/node/core/messaging/handling/agreement.rs
> +        let chosen_candidates = self.split_barrier.write().await.process(
okay seems fair to follow that up to get this in 👍

2022-04-25 14:38 UTC, joshuef commented on sn_node/src/node/handover/handover_consensus.rs
> +        info!("[HDVR] {:?} handling vote: {:?}", self.id(), signed_vote);
we need to watch what we're logging. Is this useful after this PR? (for sure its not info level)

2022-04-25 14:38 UTC, joshuef commented on sn_node/src/node/handover/handover_consensus.rs
> +        info!("[HDVR] {:?} handling vote: {:?}", self.id(), signed_vote);
we need to watch what we're logging. Is this useful after this PR? (for sure its not info level)

2022-04-25 14:38 UTC, joshuef commented on sn_node/src/node/core/messaging/handling/handover.rs
> +        debug!(
is this (and the following) debug level? Do we need to see the whole vote?

2022-04-25 14:38 UTC, joshuef commented on sn_node/src/node/core/messaging/handling/handover.rs
> +        debug!(
is this (and the following) debug level? Do we need to see the whole vote?

2022-04-25 14:38 UTC, joshuef commented on sn_node/src/node/core/messaging/sending/handover.rs
> +                debug!(">>> {}: {:?}", LogMarker::HandoverConsensusTrigger, &vote);
Also lets remove `>>>` from the log msgs. (and the votes again if they're big and /or useless beyond debuggin this pr)

2022-04-25 14:38 UTC, joshuef commented on sn_node/src/node/core/messaging/sending/handover.rs
> +                debug!(">>> {}: {:?}", LogMarker::HandoverConsensusTrigger, &vote);
Also lets remove `>>>` from the log msgs. (and the votes again if they're big and /or useless beyond debuggin this pr)

2022-05-03 07:23 UTC, joshuef commented
closing as merged via #1155

2022-05-03 07:23 UTC, closed without merging