Check incoming authed SAP in signed votes
maidsafe/safe_network pull request #1168
Opened 2022-05-05 17:52 UTC by grumbach

- Make sure incoming vote's auth'd SAPs are correctly signed by elders before we forward them to consensus.

2022-05-05 19:36 UTC, grumbach commented
Seems like the test `split_network_assert_health_check ` is failing on the latest main branch as well (without the changes included in this PR)

2022-05-06 12:59 UTC, grumbach commented
> Seems like the test `split_network_assert_health_check ` is failing on the latest main branch as well (without the changes included in this PR)

Now should be fixed

2022-05-10 09:41 UTC, joshuef commented on sn_node/src/node/core/messaging/handling/handover.rs
> +            error!("Ignoring invalid handover vote: {}", err);
Let's return an error here. I think we can then look to hook into dysfunction in a layer above.

2022-05-10 09:45 UTC, joshuef requested changes
Return an error in order to react above to dysfunction there.

2022-05-10 13:18 UTC, joshuef approved these changes

2022-05-10 13:18 UTC, joshuef commented
bors r+

2022-05-10 14:27 UTC, merged