fix: make dbc reissue working in Windows
maidsafe/safe_network pull request #1224
Opened 2022-06-08 14:57 UTC by maqi

2022-06-09 07:29 UTC, joshuef requested changes
@maqi can we add a test for this? As I think we should have caught this issue on CI.

2022-06-09 09:51 UTC, maqi commented
> @maqi can we add a test for this? As I think we should have caught this issue on CI.

Ok, will have a check where is the suitable place to add a test in.

2022-06-09 12:39 UTC, bochaco commented on sn_interface/src/network_knowledge/prefix_map/mod.rs
> +    pub fn insert(&self, sap: SectionAuth<SectionAuthorityProvider>) -> bool {
This is not meant to be allowed in the public API as the comment above suggest, do we need it to be public for tests? if so perhaps expose a public api which is only enable in test feature? see the reason why you break encapsulation if you just make it public in the comment above.

2022-06-09 12:50 UTC, maqi commented on sn_client/src/connections/messaging.rs
> +        let (elders, section_pk) = if let Some(sap) = a_close_sap {
line 506 is required for the later on verification of elders.len() of the SAP to be valid.
According to the comment at line 520, it seems the verification is still necessary.

2022-06-09 12:58 UTC, bochaco commented on sn_client/src/connections/messaging.rs
> +        let (elders, section_pk) = if let Some(sap) = a_close_sap {
what I meant, is that L506 does the same as the `if let Some(sap) = a_close_sap`, so you can return it from there rather than from L506

2022-06-13 14:13 UTC, joshuef approved these changes

2022-06-13 14:13 UTC, joshuef commented
bors r+

2022-06-14 06:42 UTC, maqi commented
bors r+

2022-06-14 07:53 UTC, merged