refactor(prefix_map): move SectionChain into NetworkPrefixMap
maidsafe/safe_network pull request #1334
Opened 2022-07-14 10:50 UTC by RolandSherwin

2022-07-18 11:50 UTC, RolandSherwin commented on sn_interface/src/network_knowledge/prefix_map/mod.rs
> +    pub section_dag: Arc<RwLock<SecuredLinkedList>>,
Used in client's `Session` which spawns tasks, hence the struct has to be `Sync`

2022-08-01 15:08 UTC, davidrusu reviewed
**Edit: Just realized that `format!("{:?}", prefix_map.genesis_key())` predates your changes, we can hold off on this suggestion in this PR:**

using `format!("{:?}", prefix_map.genesis_key())` as the filename is a hack and will change each time someone changes the `Display` impl for BLS keys, lets do something more robust.

i.e. try:

`NetworkPrefixMap::genesis_key_hex() -> String`

That returns the genesis key as a hex-encoded string, you can use that as a filename reliably and won't depend on the BLS display impl.

2022-08-01 15:21 UTC, davidrusu commented on sn_cli/src/operations/config.rs
> +            serialized_config: Option<String>,
change this to `config: Option<Settings>` and do the serializing to JSON only inside this function.

2022-08-01 15:27 UTC, davidrusu commented on sn_cli/src/operations/config.rs
> +        };
```suggestion
        assert!(matches!(
            network_info,
            NetworkInfo::Local(_, Some(genesis_key)) if genesis_key == prefix_map.genesis_key())
        )
```

2022-08-01 15:44 UTC, davidrusu commented on sn_interface/src/network_knowledge/mod.rs
> +    pub fn mut_prefix_map(&mut self) -> &mut NetworkPrefixMap {
Convention is for `mut` on the end: `<name>_mut()`, i.e. `iter_mut()`

```suggestion
    pub fn prefix_map_mut(&mut self) -> &mut NetworkPrefixMap {
```

2022-08-01 15:45 UTC, davidrusu commented on sn_interface/src/network_knowledge/mod.rs
> +    // removed; else have to make a lot of fns as async
Seems like you've resolved this TODO already?

2022-08-01 15:58 UTC, RolandSherwin commented on sn_interface/src/network_knowledge/mod.rs
> +    // removed; else have to make a lot of fns as async
I'm writing a follow up PR to make changes to `NetworkKnowledge` struct, so including the changes there.

2022-08-01 16:38 UTC, davidrusu commented on sn_interface/src/network_knowledge/prefix_map/mod.rs
> +        self.sections.get(prefix).map(|sap| sap.value.clone())
Use your helpers when available
```suggestion
        self.get_signed(prefix).map(|sap| sap.value)
```

2022-08-01 19:32 UTC, davidrusu commented on sn_interface/src/network_knowledge/prefix_map/mod.rs
>                  }
```suggestion
                Some(prefix) != exclude
```

2022-08-01 19:44 UTC, davidrusu commented on sn_interface/src/network_knowledge/utils/mod.rs
> +    let tmp_prefix_map_file = prefix_map_dir.join(format!("temp-{:?}", prefix_map.genesis_key()));
You should be using the `tempfile` crate here (we already have it as a dependency). 

You still have over-write corruption issues with this algorithm since the temp file is deterministically named. i.e. all nodes running locally are using the same temp file.

2022-08-01 19:47 UTC, davidrusu requested changes
Some good work here, but there's a few changes that are needed still

2022-08-02 06:17 UTC, RolandSherwin commented on sn_interface/src/network_knowledge/utils/mod.rs
> +    let tmp_prefix_map_file = prefix_map_dir.join(format!("temp-{:?}", prefix_map.genesis_key()));
Oh yeah, that's right! Updating it!

2022-08-02 07:17 UTC, RolandSherwin commented on sn_cli/src/operations/config.rs
> +        };
This is really helpful! Found a couple more places where I replaced the match statements. Everything is much cleaner now!

2022-08-02 08:33 UTC, RolandSherwin commented on sn_interface/src/network_knowledge/prefix_map/mod.rs
> +        self.sections.get(prefix).map(|sap| sap.value.clone())
Aye! Will keep that in mind :+1:

2022-08-02 13:18 UTC, davidrusu commented on sn_cli/src/operations/config.rs
> +        };
I assume this will be replaced with `tempfile` once #1433 is in?

2022-08-02 13:20 UTC, RolandSherwin commented on sn_cli/src/operations/config.rs
> +        };
Aye! I will move this change to #1433

2022-08-02 13:34 UTC, RolandSherwin commented on sn_interface/src/network_knowledge/utils/mod.rs
>          .map_err(|e| Error::FileHandling(e.to_string()))?;
Rename is not atomic if `/tmp` is on a different mount point. So wanted to mitigate that.

2022-08-02 13:35 UTC, davidrusu commented on sn_interface/src/network_knowledge/utils/mod.rs
>          .map_err(|e| Error::FileHandling(e.to_string()))?;
@RolandSherwin sorry yeah realized /tmp is not what we want, I updated the comment after I wrote it, please check again

2022-08-03 15:33 UTC, davidrusu approved these changes
:ship: good stuff

2022-08-04 19:18 UTC, merged