fix: propose offline against nodes having the same conn info
maidsafe/safe_network pull request #1336
Opened 2022-07-14 15:41 UTC by maqi

2022-07-14 17:11 UTC, davidrusu commented on sn_node/src/node/messaging/agreement.rs
> +        //   2, Its age is higher than the incoming node by just 1.
This validation should be done in the membership validations to prevent even accepting these nodes into the network in the first place.

Consider moving this logic to `NodeState::validate` here:
https://github.com/maidsafe/safe_network/blob/main/sn_interface/src/network_knowledge/node_state.rs#L71

`NodeState::validate` is called by Membership before it is proposed.

You'll need to modify the `Validate` function to take something like `members: BTreeMap<XorName, NodeState>` instead of the current `members: BTreeSet<XorName>`.

2022-07-14 17:15 UTC, davidrusu commented on sn_node/src/node/messaging/agreement.rs
> +            let incoming_age = new_info.age();
Consider modifying the `get_name_by_conn_info()` helper to return a `Peer` or a `NodeState` so that we can use the `age()` methods.

```suggestion
        if let Some(existing_peer) = self
            .network_knowledge
            .get_peer_by_conn_info(&new_info.addr())
        {
            let existing_age = existing_peer.age();
            let incoming_age = new_info.age();
```

2022-07-15 05:36 UTC, joshuef commented on sn_node/src/node/messaging/agreement.rs
> +                cmds.push(Cmd::ProposeOffline(list));
I think we should try and keep all offline proposals to be kicked off via dysfunction. That way we have _one_ place that's the decision center for node punishment.

We should here instead (if we cannot avoid this altogether as @davidrusu suggests): write something to sn_dysfunction (a new `IssueType`), which will basically _always_ result in the node being returned as `dysfunctional`.

2022-07-18 09:38 UTC, maqi commented on sn_node/src/node/messaging/agreement.rs
> +        //   2, Its age is higher than the incoming node by just 1.
I checked the code of `NodeState::validate` and the correspondent place calling it.
It seems the validation will be carried out agaisnt all received proposal shares?
If so, this will be quite in-efficient and even need to pass in additional parameter of `connection_info` in ? 

Also, if want to make dyfunction to be responsible of casting the offline vote, move the validate into `node_state` will become tricky.

So, I'd prefer leave the work of move it to `NodeState::validate` as a separte task/PR afterwards, if really decided to do so.

2022-07-18 09:40 UTC, maqi commented on sn_node/src/node/messaging/agreement.rs
> +        //   2, Its age is higher than the incoming node by just 1.
I checked the code of `NodeState::validate` and the correspondent place calling it.
It seems the validation will be carried out agaisnt all received proposal shares?
If so, this will be quite in-efficient and even need to pass in additional parameter of `connection_info` in ? 

Also, if want to make dyfunction to be responsible of casting the offline vote, move the validate into `node_state` will become tricky.

So, I'd prefer leave the work of move it to `NodeState::validate` as a separte task/PR afterwards, if really decided to do so.

2022-07-19 10:36 UTC, maqi commented on sn_node/src/node/messaging/agreement.rs
> +        //   2, Its age is higher than the incoming node by just 1.
> would the overall vote to join not fail though (for the duplicate node) if enough nodes have the check

There is still chance the invalid one passed the vote first before the valid one.
With enough nodes have the check, the consequence will be `valid one` get rejected by mistake.

2022-07-19 11:24 UTC, joshuef requested changes

2022-07-22 08:51 UTC, joshuef commented
closing, as superseded by healthcheck #1375

2022-07-22 08:51 UTC, closed without merging