feat(membership-decision): join approval has membership decision
maidsafe/safe_network pull request #1338
Opened 2022-07-14 17:38 UTC by davidrusu

This PR changes our Join approval flow to include the membership decision that approved the node to join the section.

2022-07-14 17:39 UTC, davidrusu commented on sn_interface/src/network_knowledge/section_authority_provider.rs
> +    pub fn section_decision<P: Proposition>(
Test helper for creating any `sn_consensus::Decision<T>`

2022-07-14 19:37 UTC, davidrusu commented on sn_node/src/node/messaging/agreement.rs
> -    pub(crate) async fn handle_online_agreement(
This handler has been renamed to `handle_join_decision()` and moved to the `messaging/membership.rs` module.

2022-07-14 19:40 UTC, davidrusu commented on sn_node/src/node/messaging/membership.rs
> +        if let Some((_, sig)) = joining_nodes.iter().max_by_key(|(_, sig)| sig) {
Now only one churn id is created per generation, previously a churn id was created for each node that joined in that generation.

We use the largest signature of the nodes that joined this generation as the ChurnId

2022-07-15 05:38 UTC, joshuef requested changes
Changes look good. Though there's some failing node tests there

2022-07-22 21:27 UTC, davidrusu commented on sn_node/src/node/cfg/config_handler.rs
> -
We've dropped support for rejoins in this PR

2022-07-22 21:29 UTC, davidrusu commented on sn_node/src/node/flow_ctrl/tests/mod.rs
> -
We no longer support rejoins as of this PR so the various scenarios have been reduced down to the one "ensure we don't let nodes rejoin" scenario above

2022-07-23 21:50 UTC, oetyng approved these changes

2022-07-23 21:50 UTC, oetyng commented on sn_node/src/node/flow_ctrl/tests/mod.rs
> +            // A rejoining node with always be rejected
with => will

2022-07-23 21:55 UTC, merged