chore: refactor CmdCtrl, naming and remove retries
maidsafe/safe_network pull request #1402
Opened 2022-07-27 10:10 UTC by joshuef

- removes Cmd retries as unused.
- Removes clone from `FlowCtrl`, 
- unifies periodic Cmd checks into ont loop

2022-07-27 18:34 UTC, oetyng requested changes

2022-07-27 18:34 UTC, oetyng commented on sn_node/src/node/flow_ctrl/mod.rs
> +                for peer in data_recipients.iter() {
this loop, if it's to get owned peers within the collection, then a copied/cloned thingie instead should work?

2022-07-27 18:34 UTC, oetyng commented on sn_node/src/node/flow_ctrl/mod.rs
> +            if let Some(msg) = self.incoming_msg_events.recv().await {
It seems adults are not listening to incoming msgs when this block is down here?
It would need to go at line 100 to be executed by adults as well.

Another thing though, is that the periodic checks are then driven by us receiving msgs.
Probably that is okay. But could cause some strange gaps.

An option would be to use `try_recv` api on the receiver, and do a tiny sleep (to not have the cpu race) if returning `Err(TryRecvError::Empty)`. So, the sleep length would be around the interval we'd expect to check for new msgs (I don't know what value we want there).

2022-07-28 08:09 UTC, joshuef commented on sn_node/src/node/flow_ctrl/mod.rs
> +            if let Some(msg) = self.incoming_msg_events.recv().await {
yeh good catch!

2022-07-28 08:33 UTC, joshuef commented on sn_node/src/node/flow_ctrl/mod.rs
> +                debug!("msggggeventtt");
nop!

2022-08-16 07:27 UTC, joshuef commented
Closing as merged main changes in via #1465

2022-08-16 07:27 UTC, closed without merging