chore(cli): atomic write of cli/config.json
maidsafe/safe_network pull request #1433
Opened 2022-08-02 11:00 UTC by RolandSherwin

Fixes the write corruption when running CLI tests using multiple threads.
Note: Uses `thread_rng()` to generate a random filename, as `tempfile` will introduce a new dependency to CLI.

2022-08-02 11:30 UTC, joshuef approved these changes

2022-08-02 11:31 UTC, joshuef commented
bors r+

2022-08-02 12:37 UTC, davidrusu requested changes
Should use the `tempfile` crate instead of generating random names by hand.

2022-08-02 12:37 UTC, davidrusu commented on sn_cli/src/operations/config.rs
> +        };
Any reason why we aren't using the `tempfile` crate here?

2022-08-02 12:37 UTC, davidrusu commented
bors cancel

2022-08-02 12:42 UTC, RolandSherwin commented on sn_cli/src/operations/config.rs
> +        };
Did not want to introduce a new dep, will make changes to use `tempfile` if `thread_rng()` has a possibility to generate the same value.

2022-08-02 12:58 UTC, davidrusu commented on sn_cli/src/operations/config.rs
> +        };
It's actually already a dependency of `sn_cli` you can see it with:

    cargo tree -p sn_cli -i tempfile

It's pulled in through multiple other dependencies.

2022-08-02 13:00 UTC, RolandSherwin commented on sn_cli/src/operations/config.rs
> +        };
Aha! That's quite useful! Making the changes right now..

2022-08-02 20:27 UTC, davidrusu commented on sn_cli/src/operations/config.rs
> +            .await
We have the file opened when `temp_file` was instantiated, so we can just write to it directly with `write_all`. `fs::write` will re-open the file and then write.

```suggestion
        temp_file.write_all(serialized)
```

2022-08-03 07:18 UTC, RolandSherwin commented on sn_cli/src/operations/config.rs
> +            .await
I have made the changes, but my thought was to make the write async, `tempfile` is sync only. So I assume the cost of opening the file > sync writes?

2022-08-03 12:38 UTC, davidrusu commented on sn_cli/src/operations/config.rs
> +            .await
>So I assume the cost of opening the file > sync writes?

Possibly, but it's so infrequent that I don't think it will even register.

2022-08-03 12:40 UTC, davidrusu approved these changes
Thanks! good changes throughout

2022-08-03 15:24 UTC, merged