feat(sections_dag): replace `SecuredLinkedList` with `SectionsDAG`
maidsafe/safe_network pull request #1527
Opened 2022-08-29 06:49 UTC by RolandSherwin

2022-09-14 13:49 UTC, bochaco commented on sn_node/src/node/error.rs
> +    PeerLinkDropped(Peer),
It seems we don't need this error type?

2022-09-14 13:49 UTC, bochaco commented on sn_node/src/node/dkg/session.rs
> +const MAX_TIMEOUT_RETRIES: usize = 25;
I guess we don't need this change in this PR as they changes shouldn't affect our DKG process?

2022-09-14 14:23 UTC, RolandSherwin commented on sn_node/src/node/error.rs
> +    PeerLinkDropped(Peer),
Sorry, I might have messed up a rebase.. removed it!

2022-09-14 16:15 UTC, bochaco requested changes

2022-09-14 16:15 UTC, bochaco commented on sn_interface/src/network_knowledge/section_tree/mod.rs
> +            return Err(Error::MultipleBranchError);
I think this error should be returned **only** when the condition `partial_dag.leaf_keys().len() == 1` is not met, the other part of the condition shouldn't be throwing this error type

2022-09-14 16:15 UTC, bochaco commented on sn_interface/src/network_knowledge/section_tree/mod.rs
> -            return Err(Error::UntrustedSectionAuthProvider(format!(
We still want this check and the error returned can still be the same

2022-09-15 09:53 UTC, RolandSherwin commented on sn_interface/src/network_knowledge/section_tree/mod.rs
> -            return Err(Error::UntrustedSectionAuthProvider(format!(
Moved this check above the part where we query the SectionTree

2022-09-15 15:01 UTC, davidrusu commented on sn_interface/src/network_knowledge/mod.rs
> +        if genesis_key != *dag.genesis_key() {
We have a lot of genesis key validations in this constructor and I think it's an artifact of these 3 parameters we are taking in:
- genesis_key
- SectionsDag
- passed_section_tree

Each of these have a "genesis key" and we need to ensure that they all agree.

It would be better if we had a single parameter that has a genesis key so that we don't have to validate.

It seems that the single param would be the `SectionTree`. Instead of taking an option `passed_section_tree: Option<SectionTree>`, we can force the caller to construct the `SectionTree` before calling the `NetworkKnowledge` constructor.

Don't do this in this PR, we can look at it next.

2022-09-15 15:14 UTC, davidrusu commented on sn_interface/src/network_knowledge/mod.rs
> +        };
I don't think it's worth having this check here, it should never happen and we can detect if it happens from the `trace` log above that prints both booleans

2022-09-15 15:15 UTC, davidrusu commented on sn_interface/src/network_knowledge/mod.rs
>      /// Return current section chain length
```suggestion
    /// Return the number of keys in our section dag
```

2022-09-15 15:16 UTC, davidrusu commented on sn_interface/src/network_knowledge/mod.rs
>      /// Return a vec of all known keys
```suggestion
    /// Return the set of known keys
```

2022-09-15 15:18 UTC, davidrusu commented on sn_interface/src/network_knowledge/section_authority_provider.rs
> +    // Get `Prefix` from st
```suggestion
    // Parse `Prefix` from string
```

2022-09-15 15:25 UTC, davidrusu commented on sn_interface/src/network_knowledge/section_tree/mod.rs
> +        if !partial_dag.leaf_keys().contains(&signed_sap.section_key()) {
I think you can combine these last two checks with
```suggestion
        if partial_dag.leaf_keys() != BTreeSet::from_iter([signed_sap.section_key()]) {
```
Also make sure to log `partial_dag.leaf_keys()` in the error msg string as well.

2022-09-15 15:28 UTC, davidrusu commented on sn_interface/src/network_knowledge/section_tree/mod.rs
> +                );
nit. save some vertical space
```suggestion
                debug!("Known prefix, section_key after update: {prefix:?} = {section_key:?}");
```

2022-09-15 15:37 UTC, RolandSherwin commented on sn_interface/src/network_knowledge/section_tree/mod.rs
> +        if !partial_dag.leaf_keys().contains(&signed_sap.section_key()) {
Since `partial_dag` can contain a tree with more than one branch, the `MultipleBranchError` was introduced to specify that we expect a dag with just 1 branch. So, is it ok to separate out the errors?

2022-09-15 15:43 UTC, RolandSherwin commented on sn_interface/src/network_knowledge/mod.rs
> +        if genesis_key != *dag.genesis_key() {
Yeah, will try to include it in the following cleanup PR.

2022-09-15 15:47 UTC, davidrusu commented on sn_interface/src/network_knowledge/sections_dag.rs
> +        }
Do you want to move this struct out, derive Serialize for it and use it for the serializer as well at https://github.com/maidsafe/safe_network/pull/1527/files#diff-600741ddfc9d4fdd3347d88539faa1a20b920bab3d6349e726c67ca851c075e8R86-R89?

2022-09-15 15:56 UTC, davidrusu commented on sn_interface/src/network_knowledge/sections_dag.rs
> +        }
That parent key position() call will make this debug impl quadratic as well, and I imagine we may be logging this quite frequently. Lets pre-index the keys to avoid any slowdown.
```suggestion
        let keys: Vec<_> = self.keys().cloned().collect();
        let key_positions: BTreeMap<&PublicKey, usize> = keys.iter().enumerate().collect();
        let mut parent_indices: Vec<usize> = Vec::new();
        for key in keys.iter() {
            match self.get_parent_key(key).map_err(|_| fmt::Error)? {
                None => parent_indices.push(usize::MAX),
                Some(parent_key) => {
                    let idx = key_positions.get(&parent_key).ok_or(fmt::Error)?;
                    parent_indices.push(idx)
                }
            }
        }
```

2022-09-15 16:04 UTC, davidrusu commented on sn_node/src/node/messaging/mod.rs
>          NetworkKnowledge::verify_node_msg_can_be_trusted(msg_authority, msg, &known_keys)
Consider modifying `verify_node_msg_can_be_trusted` to take the set rather than the vec. It should improve validation perf. (and remove the vec conversion)

2022-09-15 16:08 UTC, RolandSherwin commented on sn_interface/src/network_knowledge/sections_dag.rs
> +                self.child_nodes(current_node.hash())
The order is important because we perform `insert()` while deserializing, and we want to make sure we insert the parent before the child. 

Traversing from the root makes sense, but we will be adding a lot of duplicate elements to the `Vec` as we might visit the same parent multiple times. Do you think it's worth keeping a separate `BTreeSet` which we can query to check if a parent `SectionInfo` has been inserted into the Vec, if so we can go ahead with the next leaf.

We have the same logic in `self_verify`
```rust
// we stop when parent is verified; meaning all ancestors are verified.
if verified_keys.contains(&parent) {
    break true;
}
```

2022-09-15 16:09 UTC, davidrusu commented on sn_node/src/node/mod.rs
> +                    .collect::<Vec<_>>()[0];
This seems to be a common pattern, lets make it a method

2022-09-16 16:47 UTC, RolandSherwin commented on sn_interface/src/network_knowledge/sections_dag.rs
> +        }
Yeah, that would make more sense! Changed it!

2022-09-16 16:52 UTC, RolandSherwin commented on sn_interface/src/network_knowledge/sections_dag.rs
> +        }
Updated it!

2022-09-20 01:28 UTC, davidrusu commented on sn_interface/src/network_knowledge/sections_dag.rs
> +}
Good stuff 👍

2022-09-20 01:33 UTC, davidrusu approved these changes
👍 looks good

2022-09-20 01:34 UTC, davidrusu commented on sn_interface/src/network_knowledge/section_tree/mod.rs
> +        if !partial_dag.leaf_keys().contains(&signed_sap.section_key()) {
ok, yeah makes sense, I saw you testing for that error variant in some test cases.

2022-09-20 01:35 UTC, davidrusu commented on sn_interface/src/network_knowledge/sections_dag.rs
> +                self.child_nodes(current_node.hash())
The new implementation you did looks good 👍

2022-09-20 17:07 UTC, davidrusu commented
bors r+

2022-09-20 20:01 UTC, davidrusu commented
bors r+

2022-09-20 21:08 UTC, merged