refactor(data): move outside of node
maidsafe/safe_network pull request #1691
Opened 2022-10-23 15:50 UTC by oetyng

BREAKING CHANGE: Name change of node msg.

2022-10-25 22:31 UTC, davidrusu reviewed
It's looking good!

My main question is why we need the `DataEvent`. Can we not have `Data::handle` return commands?

2022-10-25 22:31 UTC, davidrusu commented on sn_node/src/data/mod.rs
> +pub enum Event {
Are we still using these events for some business logic?

2022-10-25 22:31 UTC, davidrusu commented on sn_node/src/node/flow_ctrl/dispatcher.rs
> +            }
Why don't we have `data.handle(..)` returning commands as well? Any reasons why we need to use DataEvent's here?

2022-10-25 22:31 UTC, davidrusu commented on sn_node/src/node/mod.rs
> +                if adults_changed {
Is this not the same as:
```suggestion
                if current != old.adults {
```

2022-10-26 09:24 UTC, oetyng commented on sn_node/src/node/mod.rs
> +                if adults_changed {
Yes, I believe so. Remnant from when `added`, `removed` and `remaining` where used variables 👍

2022-10-26 09:31 UTC, oetyng commented on sn_node/src/data/mod.rs
> +pub enum Event {
I believe these are correct to keep, as to actually have the decoupling. Otherwise we introduce the full range of cmds into Data module, while those contain all sorts of things related to the node. It shouldn't be possible to call the node and ask it to do various things, from within data module, as that breaks inversion of control.

2022-10-26 09:36 UTC, oetyng commented on sn_node/src/node/flow_ctrl/dispatcher.rs
> +            }
It shouldn't be possible to call the node and ask it to do various things, from within data module, as that breaks inversion of control.

2022-10-26 09:45 UTC, oetyng commented on sn_interface/src/network_knowledge/node_info.rs
> +    pub fn id(&self) -> PublicKey {
Also I see that the public key is used unnecessarily for those flows, since old.

2022-10-28 02:52 UTC, davidrusu approved these changes
:ship:

2022-10-28 02:52 UTC, davidrusu commented
bors r+

2022-10-30 22:28 UTC, joshuef requested changes
I think we need to break this up more. 

There's some renaming here that could go in it's own PR that'll be much easier to get in. So it'd be great to get those pulled out as a first step.

-----

Also I'm not sold on DataEvents... I think we may need to more solidly look at the API we want of a DataStorage module.

To my mind beyond the API itself it should be a black box (so that it is replaceable with some other impl) if we're going that way. Having the `/node` code need to handle `DataEvents` feels more complex than necessary.

---

w/r/t the data API. I also think we may well be wanting some sync calls. Or at least the option of sync calls from an API standpoint (thinking w/r/t returning ACKs only when data has been stored)

2022-10-30 22:28 UTC, joshuef commented on sn_node/benches/data_storage.rs
> +                let storage = get_new_register_store()
Can we maintain one interface for storing of data. Feels cleaner to me

2022-11-22 10:41 UTC, oetyng commented
> w/r/t the data API. I also think we may well be wanting some sync calls. Or at least the option of sync calls from an API standpoint (thinking w/r/t returning ACKs only when data has been stored)

Yeah, I'll be revisiting this later like we discussed, so we can nail the sync aspect of ACKS.

> Also I'm not sold on DataEvents... I think we may need to more solidly look at the API we want of a DataStorage module.

Sure, we'll have to figure out what makes most sense to actually reach the decoupling.

> To my mind beyond the API itself it should be a black box (so that it is replaceable with some other impl) if we're going that way. Having the `/node` code need to handle `DataEvents` feels more complex than necessary.

Absolutely agree about the black box and being able to replace it with some other impl.
Also for usage of the actual `DataStorage` in other contexts than our network (including but not limited to; examples, tests etc.).

Events, sure that is a question of both pro's and cons.

In one aspect, our whole system is basically built on events, it's just a matter of syntax and structure.
Also when it comes to testability and debugging, cmds->events has lots of benefits. (These are actually the main ones I've been hoping that we would be able to get.)

In another aspect, there is a more feature rich and specific use of events that can - and cannot - be suitable for different systems.

The most suitable types of systems using the full fledged pattern is highly concurrent systems with many different parts concurrently operating on results from other parts. And our system doesn't actually look quite like that right now (and may never do).

***

The two common approaches to decoupling that I think of now are messaging and interfaces (i.e. traits in rust).
Since we do not use traits much, and already have a fundamentally message based system, I thought the message way was appropriate.

But the devils are in the details, so we'll have to look into the tradeoffs closer.

One way or another, I still think we really should decouple `DataStorage` from `MyNode`.

2022-12-08 10:07 UTC, oetyng commented
Will revisit this later.

2022-12-08 10:07 UTC, closed without merging