chore(ci): kill all nodes before packaging logs to upload
maidsafe/safe_network pull request #1727
Opened 2022-11-01 17:38 UTC by bochaco

2022-11-02 01:37 UTC, joshuef requested changes

2022-11-02 01:37 UTC, joshuef commented on .github/workflows/sn_pr_tests.yml
> +  #      - name: Kill all nodes
lets remove this if we're doing it above then :+1

2022-11-02 11:33 UTC, bochaco commented on .github/workflows/sn_pr_tests.yml
> +  #      - name: Kill all nodes
do you mean in the previous step? that's only listing them...or what do you mean?

2022-11-03 12:28 UTC, joshuef commented on .github/workflows/sn_pr_tests.yml
> +  #      - name: Kill all nodes
i just meant the commented code for `kill all nodes`.

2022-11-07 18:37 UTC, bochaco commented on .github/workflows/sn_pr_tests.yml
> +  #      - name: Kill all nodes
But the earlier one is for the other job, i.e. `e2e` job, this one is for whenever we re-enable `e2e-split` job, sorry, but I don't think I understand?

2022-11-09 23:43 UTC, joshuef commented on .github/workflows/sn_pr_tests.yml
> +  #      - name: Kill all nodes
Ahhh, no. I don't think _i_ understood. All good then

2022-11-09 23:43 UTC, joshuef commented
bors r+

2022-11-09 23:44 UTC, joshuef approved these changes

2022-11-11 20:06 UTC, bochaco commented
bors r+

2022-11-11 20:55 UTC, merged