refactor(responses): return correct cmd response
maidsafe/safe_network pull request #1766
Opened 2022-11-18 17:52 UTC by oetyng

- Returns the ack corresponding to the cmd.
- Renames `ClientMsgResponse` to `ClientDataResponse`.
- Makes `NodeDataResponse` be handled like `ClientDataResponse`.
- Moves data write acks to `NodeDataReponse`.
- Makes `NodeEvent` only be Adult to Elder notifications.

2022-11-20 08:49 UTC, joshuef commented on sn_client/src/connections/listeners.rs
> +                    Box::new(Error::AntiEntropyMaxRetries {
How come we need a `Box` now?

2022-11-20 08:49 UTC, joshuef commented on sn_interface/src/messaging/data/mod.rs
> +    #[allow(clippy::result_large_err)]
What's making this large error here? 

(i'm concious we just reworked some things to avoid this error, so if we can avoid it, that'd be suuuper)

2022-11-20 08:49 UTC, joshuef commented on sn_interface/src/types/errors.rs
> +    InvalidOperation(String),
Can we add concrete errors for what we need here? 

It's good to avoid these catchall `String` error types as they always seem to get abused a bit later.

2022-11-20 08:51 UTC, joshuef requested changes
Can we add concrete types for the errors to avoid the catchall `String`?

2022-11-20 11:42 UTC, oetyng commented on sn_client/src/connections/listeners.rs
> +                    Box::new(Error::AntiEntropyMaxRetries {
It was a clippy warning.
Maybe showed up before i updated rust. Will check.

2022-11-20 11:45 UTC, oetyng commented on sn_interface/src/messaging/data/mod.rs
> +    #[allow(clippy::result_large_err)]
I'm really not sure, it was weird actually for the warning to show up.

2022-11-20 12:40 UTC, oetyng commented on sn_interface/src/types/errors.rs
> +    InvalidOperation(String),
Yeah I agree. But we already have it in other errors though.

The concrete error in this case is a bit silly.

When getting the correct error from a ReplicatedData we do this:

```
ReplicatedData::RegisterLog(_) => {
                return Err(Error::InvalidOperation(
                    "RegisterLog is not resulting from a cmd.".to_string(),
                ))
            }
            ReplicatedData::SpentbookLog(_) => {
                return Err(Error::InvalidOperation(
                    "SpentbookLog is not resulting from a cmd.".to_string(),
                ))
            }
```

When producing an error CmdResponse we do this
```
Self::SpentbookLog(_) => Err(Error::InvalidOperation(
                "There is no CmdResponse for the SpentbookLog variant of ReplicatedData."
                    .to_string(),
            )),
            Self::RegisterLog(_) => Err(Error::InvalidOperation(
                "There is no CmdResponse for the RegisterLog variant of ReplicatedData."
                    .to_string(),
            )),
```

(Converting those to specific errors  would be like `CannotGetACmdErrorFromRegisterLog` which seems... meh.

2022-11-20 12:44 UTC, oetyng commented on sn_interface/src/types/errors.rs
> +    InvalidOperation(String),
These are really unreachable paths that should eventually be designed out, if we can do that in a sane way.

2022-11-20 12:47 UTC, oetyng commented on sn_client/src/connections/listeners.rs
> +                    Box::new(Error::AntiEntropyMaxRetries {
It's because the Error itself has variants that contain the same large stuff like `QueryResponse`, `NodeMsg` and so on.

2022-11-20 16:31 UTC, oetyng commented on sn_client/src/connections/listeners.rs
> +                    Box::new(Error::AntiEntropyMaxRetries {
I just checked now by removing the box. The warning came before but was not there now. So no need for the `Box`!

Will fix 👍

2022-11-20 16:35 UTC, oetyng commented
> Can we add concrete types for the errors to avoid the catchall `String`?

Hey, check this https://github.com/maidsafe/safe_network/pull/1766#discussion_r1027283000
What do you think?

2022-11-20 22:27 UTC, joshuef approved these changes

2022-11-20 22:28 UTC, joshuef commented
bors r+

2022-11-20 23:28 UTC, merged

2022-11-21 00:48 UTC, joshuef commented
okay, we actually have the `large_enum` clippy skipper throughout the code. I didn't realise that, so let's ignore that for this PR.