Ae lock reduction2
maidsafe/safe_network pull request #1767
Opened 2022-11-19 12:44 UTC by joshuef

2022-11-19 12:44 UTC, joshuef commented
bors try

2022-11-19 22:37 UTC, joshuef commented
bors try

2022-11-20 08:43 UTC, joshuef commented
bors try

2022-11-20 16:26 UTC, oetyng approved these changes
Nice one!

2022-11-20 16:26 UTC, oetyng commented on sn_node/src/node/messaging/node_msgs.rs
> +                MyNode::handle_anti_entropy_msg(node, &context, section_tree_update, kind, sender)
Shouldn't need to pass in a borrow of the context, since it is not used afterwards. Can be consumed.

2022-11-20 16:26 UTC, oetyng commented on sn_node/src/node/messaging/node_msgs.rs
> +                MyNode::store_data_as_adult_and_respond(&context, data, send_stream, sender, msg_id)
Same here: shouldn't need to pass in a borrow of the context, since it is not used afterwards. Can be consumed.

2022-11-20 16:34 UTC, oetyng requested changes
Ach, missed to pick the Request changes option in the first review.

2022-11-20 22:08 UTC, joshuef commented on sn_node/src/node/messaging/anti_entropy.rs
> +    /// Operates on the context mutably
Ah right yeh. I had id operating on the context before, but figured that could lead to unintended consequences for us down the line. Better to do a clean clone and never actually update the context during these checks.

2022-11-21 00:49 UTC, joshuef commented
bors try

2022-11-21 12:48 UTC, oetyng approved these changes

2022-11-21 22:22 UTC, joshuef commented
bors r+

2022-11-21 22:22 UTC, joshuef commented
bors r-

2022-11-21 22:22 UTC, merged