chore(node): Remove locks in data replication flows.
maidsafe/safe_network pull request #1769
Opened 2022-11-20 07:44 UTC by joshuef

Moves the replication flow to be outwith of node, using channels to gather data and send it in another thread entirely. This should remove another cause of serious node.write().lock usage

2022-11-20 13:24 UTC, oetyng approved these changes
Nice. Looks good.

I like that we remove the periodic check and the randomness of the replication instant.
More work will be coming in this area I feel.

2022-11-20 13:24 UTC, oetyng commented on sn_node/src/node/error.rs
> +    DataReplicationChanel,
Typo-nit: `DataReplicationChanel` => `DataReplicationChannel`

2022-11-20 13:24 UTC, oetyng commented on sn_node/src/node/flow_ctrl/dispatcher.rs
>  // Cmd Dispatcher.
The tiniest of nits perhaps, but a space between usings and the following code should be better? It's the convention I follow at least.

2022-11-20 13:24 UTC, oetyng commented on sn_node/src/node/flow_ctrl/dispatcher.rs
> +                // // we should queue this
Remove commented out code.

2022-11-20 13:24 UTC, oetyng commented on sn_node/src/node/flow_ctrl/mod.rs
>  use std::sync::Arc;
Also super-nit: But the convention I follow with the structure of usings, is to put space between the different levels of proximity to our code base.
I use this order, and when several of any, I put space between.
```
super
crate
sn_
[other crates by maidsafe]
third party
```

2022-11-20 13:24 UTC, oetyng commented on sn_node/src/node/flow_ctrl/mod.rs
> +            let node_data_storage = node_for_data_replication.read().await.data_storage.clone();
Can we clone the data storage before ln 79, to avoid doing a read lock within this async task?

So, on line 62 we can do

```
let node_identifier = node.read().await.info().name();
let node_data_storage = node.read().await.data_storage.clone();
```

Also we avoid a node clone by that.

2022-11-20 13:24 UTC, oetyng commented on sn_node/src/node/flow_ctrl/mod.rs
> +            while let Some((data_addresses, peer)) = data_replication_receiver.recv().await {
I feel this while loop can be made simpler.. But not a biggie for this PR. So, just a note.

The deduping if going to many peers depends a bit on what pattern we'll have with new peers. How what will the churn process look like and how likely are multiple peers to need bunch of same data like this?

(Connects a bit to the "hit the road running" node join process I've been thinking about).

2022-11-20 16:33 UTC, oetyng requested changes
Ach, missed to pick the `Request changes` option in the first review.

2022-11-20 22:21 UTC, joshuef commented on sn_node/src/node/flow_ctrl/mod.rs
> +            let node_data_storage = node_for_data_replication.read().await.data_storage.clone();
Ah, i did try that, but then we're doing an await in non-async code. A `block_on` or making the fn async seemed overkill. 

The lock is taken just once at startup, so maybe that's fine?

2022-11-20 22:22 UTC, joshuef commented on sn_node/src/node/flow_ctrl/mod.rs
> +            while let Some((data_addresses, peer)) = data_replication_receiver.recv().await {
Aye, initially I had that w/o the `batch`, but we could get gbs in one msg... Which network wise, should be fine. But it'd be holding a looot in mem, which is probs less fine.

2022-11-21 12:42 UTC, oetyng approved these changes

2022-11-21 12:43 UTC, oetyng commented on sn_node/src/node/flow_ctrl/mod.rs
> +            while let Some((data_addresses, peer)) = data_replication_receiver.recv().await {
Yeah, it's what goes in mem that will be an issue.

2022-11-21 12:45 UTC, oetyng commented on sn_node/src/node/flow_ctrl/mod.rs
> +            let node_data_storage = node_for_data_replication.read().await.data_storage.clone();
Aha, ah I missed that it was non-async code there. Well, I see. Never mind then.

But just to check, holding locks across awaits was something mentioned that could be problematic, right?

2022-11-21 12:46 UTC, oetyng commented
bors r+

2022-11-21 13:47 UTC, merged