What is wrong here
maidsafe/safe_network pull request #1816
Opened 2022-11-30 04:51 UTC by joshuef

2022-11-30 04:52 UTC, joshuef commented
bors try

2022-11-30 06:12 UTC, joshuef commented
bors try

2022-11-30 13:34 UTC, bochaco commented on sn_node/src/node/error.rs
> +    MissingSiblingNetworkKnowledge,
I think having context info like the node's own/sibling section prefix will be useful in order to know which is the sibling section info missing in that node.

2022-11-30 14:34 UTC, bochaco commented on sn_client/src/api/mod.rs
> +        let mut attempts = 0;
This is wrong as per how we use it within the loop, and how we compare it against `NETWORK_PROBE_MAX_ATTEMPTS`

2022-11-30 14:49 UTC, bochaco requested changes

2022-11-30 14:49 UTC, bochaco commented on sn_client/src/api/mod.rs
> +                    tokio::time::sleep(tokio::time::Duration::from_millis(500)).await
I'm not sure we need this, the AE would be all completed within the `send_query_without_retry` lifecycle before returning, although we may need a timeout around the call to `send_query_without_retry` as I think it's not bounded and could be stuck for long?

2022-11-30 15:32 UTC, joshuef commented
bors try

2022-12-01 11:47 UTC, joshuef commented
I'm going to close this, as I have the feeling it introduces some more issues in/around too many conections being spawned and slowing us down. (I've seen big pauses where we have eg 300 incoming connections in a oner... this appears to block things, though I'm not sure why atm).

https://github.com/maidsafe/safe_network/pull/1823 is a candidate to sort this in another way

2022-12-01 11:47 UTC, closed without merging