fix: improved retry loop with max iterations
maidsafe/safe_network pull request #186
Opened 2021-07-15 14:03 UTC by grumbach

This is an attempt to fix the hanging tests that use the `retry_loop!` macro which loops indefinitely, making tests hang and hiding the repeating error.
This is my proposal for a fix: it retries a given number of times (defaults to 10 if n is not provided) and `bail`s after retrying those n times.

2021-07-15 14:34 UTC, grumbach commented on src/client/utils/test_utils/mod.rs
> +                    tokio::time::sleep(std::time::Duration::from_millis(200)).await;
```suggestion
                    tokio::time::sleep(std::time::Duration::from_millis(1000)).await;
```

2021-07-15 14:40 UTC, Yoga07 approved these changes

2021-07-15 14:42 UTC, bochaco approved these changes

2021-07-15 14:54 UTC, joshuef requested changes
We already ahve retry w backoff which does this

2021-07-15 15:25 UTC, joshuef commented
@grumbach , could be good here to unify everything; either just straight up using the funcs, or using them via macro. 

I'm not sure why we'd use one over the other to be honest (in terms of dev ux... we want the backoff property I think)... but going for one is probably a good idea

2021-07-15 15:26 UTC, joshuef commented
Perhaps it should not be a test util either and just a helper we cna export for consumers to use too?

2021-07-30 10:57 UTC, connec commented
I think this can be closed, if for no other reason than `retry_loop!` isn't used.

2021-07-30 11:01 UTC, closed without merging