Authority by construction
maidsafe/safe_network pull request #187
Opened 2021-07-15 16:46 UTC by connec

- 6e9e52300 **refactor(messaging)!: Rename `*Signed` -> `*Sig`**

  The idea here is to make it clearer that this type represents a
  possibly-unverified signature, rather than a proof that something was
  signed (e.g. verification may still need tobe performed, and the only
  way to *know* if verification is needed is to trace the code flow).
  
  Eventually, `*Signed` types will be restored that are valid by
  construction, e.g. the existence of a value is proof of authority (over
  some payload, which would still only be linked implicitly, which could
  be a future enhancement).
  
  BREAKING CHANGE: All the `messaging::*Signed` structs are now called
  `messaging::*Sig`.

- 841288d97 **feat(messaging): Add a `ClientSigned` struct for client authority proof**

  The `ClientSigned` struct can only be constructed by verifying a
  `ClientSig` for a particular payload. Thus, instances of `ClientSigned`
  can be trusted as proof that the payload indeed had a valid signature,
  and was signed by the owner of `public_key` (e.g. a holder of the
  corresponding secret key).
  
  Note that it's important that `ClientSigned` **does not** implement
  `Deserialize`, or any other trait that could allow unverified
  construction. It therefore cannot be a drop-in replacement for
  `ClientSig`, which is kind of the point as we can now introduce
  `ClientSigned` in areas where we expect the signature to be valid, then
  work our way back towards verification. Ideally we should be able to
  verify immediately and use `ClientSigned` in `MessageType`.

- 9fe01f20c **refactor(messaging)!: Use `ClientSigned` in `MessageType`**

  This is pretty non-functional currently. In fact, we end up verifying
  the signature *twice*, since we also verify in
  `routing::Core::handle_message`. We should deduplcate this in future.
  
  BREAKING CHANGE: The `MessageType::Client` variant's `client_signed`
  field has changed type.

- 270e02974 **fix(node): Ensure storage write op authority is verified**

  Previously, we would only verify the signatures of the original client
  message, not the signatures of replicated ops. With this change, a
  `ClientSigned` is now needed to apply an op, meaning the signature needs
  to be verified in order to call those functions.
  
  Currently, verifications happens quite late, inside each individual
  store. This is because the `DataExchange` content is not iterated until
  this point. We really want to do this verification earlier, however.

2021-07-15 17:04 UTC, bochaco commented on src/node/metadata/mod.rs
> +fn verify_op(client_sig: ClientSig, cmd: DataCmd) -> Result<ClientSigned> {
In cases like this, I always try to receive a ref to prevent from unnecessary data cloning, i.e. `client_sig: &ClientSig`

2021-07-15 17:13 UTC, bochaco reviewed
One thing I was considering, and trying to achieve, it is to have the messaging mod/crate to not contain any impl and simply be structs and enums with their documentation of the flow they belong to. Then all type of utilities to instantiate them to be part of other mods, e.g. routing, client, etc. Create a very clear separation of what messages and the protocol is, and what are our own set of utilities and/or impl of the protocol.

This is just a proposal, mainly so we can then publish messaging on its own and can be used not only as a protocol document but also to be used by 3rd party developers implementing their own version of nodes and clients, either in Rust or any other languages.

2021-07-21 15:48 UTC, bochaco requested changes

2021-07-21 15:48 UTC, bochaco commented on src/node/event_mapping/node_msg.rs
> +) -> Result<ClientAuthority, NodeDuty> {
I don't think this should return a `Result` but simply a NodeDuty ?

2021-07-21 15:48 UTC, bochaco commented on src/client/client_api/commands.rs
> +        client_auth: ClientAuthority,
This will be a problem for offline signing, remember this API is intended to support that, and hardware wallets. It seems that won't be possible as the user cannot build a `ClientAuthority` without providing its secret key?

2021-07-21 15:52 UTC, bochaco commented on src/client/client_api/queries.rs
> +        client_auth: ClientAuthority,
Same issue as with the change in `send_signed_command`.

2021-07-21 15:55 UTC, bochaco commented on src/client/client_api/commands.rs
> +        client_auth: ClientAuthority,
....hmmm reviewing it again, i see why it returns a `Result`...so I'll take back my comment

2021-07-21 15:58 UTC, connec commented on src/client/client_api/commands.rs
> +        client_auth: ClientAuthority,
Yeah, this is a mild nuisance with the approach. The crux of the issue is that construction of `ClientAuthority` can't be possible with invalid parts, so the only options are:

- Construct with parts and validate them (`ClientAuthority::verify(...)`) – this would work with a hardware wallet scenario, at the cost of a 'redundant' sig check ("I just generated the sig, why do I have to verify it?").
- Generate on construction, as per `ClientAuthority::new`, but this requires the keypair.

So, when I wrote this I debated between using `ClientSigned` in the API, meaning callers could provide whatever they want even if it's bogus, or using `ClientAuthority`, meaning callers would need to choose how they acquire it. I guess the way I'm imaging using the current API would look like:

```rust
let signature = sign_with_my_wallet(&payload);
let client_auth = ClientAuthority::verify(wallet_pk, signature, &payload).unwrap(); // we just created the sig
send_signed_command(...)
```

All that said, I guess we don't need the signature to be valid here, so yeah we could just use `ClientSigned`.

2021-07-21 15:59 UTC, bochaco commented on src/node/event_mapping/node_msg.rs
> +) -> Result<ClientAuthority, NodeDuty> {
....hmmm reviewing it again, i see why it returns a Result...so I take back my comment

2021-07-21 16:07 UTC, bochaco commented on src/client/client_api/commands.rs
> +        client_auth: ClientAuthority,
This is just a client and its API, so any enforcement made here is only to help the user at most. The actual check will be on the network side, so the client shouldn't be too much concerned about an invalid signature, that's not in our/its control, the user needs to provide a valid signature to get the message accepted by the network. So I think either ClientSigned or just the two parts separate as current code is good enough. 
Having the client to do such verification is something I'd doubt we want, let's let that responsibility to the user of this lib/API.

2021-07-21 16:11 UTC, connec commented on src/node/event_mapping/node_msg.rs
> +) -> Result<ClientAuthority, NodeDuty> {
Hrm, I don't thinks so, since the duty for the `Ok` case depends on the query/cmd? We only know the right `NodeDuty` based on what's received, so we could match again against `msg` but there would only be three cases and an `unimplemented!` or `unreachable!`, e.g.

```rust
fn verify_data_authority(
    msg_id: MessageId,
    origin: SrcLocation,
    msg_origin: Option<EndUser>,
    client_signed: ClientSigned,
    msg: ProcessMsg,
) -> NodeDuty {
    /* ... */
    match msg {
        ProcessMsg::Query(query) => NodeDuty::ProcessRead {
            query,
            msg_id,
            client_auth,
            origin: msg_origin.unwrap(),
        },
        ProcessMsg::Cmd(DataCmd::Chunk(cmd)) => NodeDuty::WriteChunk {
            write: cmd,
            msg_id,
            client_auth,
        },
        ProcessMsg::Cmd(cmd) => NodeDuty::ProcessWrite {
            cmd,
            msg_id,
            client_auth,
            origin: msg_origin.unwrap(),
        },
        _ => unreachable!(),
    }
}
```

Not sure I prefer that, especially for the `unreachable!`. Unless you were thinking of something else?

2021-07-21 16:12 UTC, connec commented on src/client/client_api/commands.rs
> +        client_auth: ClientAuthority,
Cool, that makes sense to me, I'll switch this back then.

2021-07-21 16:13 UTC, bochaco commented on src/node/event_mapping/node_msg.rs
> +) -> Result<ClientAuthority, NodeDuty> {
no, you are right, we cross with comments here, i understand the need of a Result there, I definitely wouldn't prefer `unreachable!()`

2021-07-21 17:41 UTC, bochaco approved these changes

2021-07-21 18:02 UTC, bochaco approved these changes

2021-07-21 18:22 UTC, merged