feat(sn_node): let elder store chunks as well
maidsafe/safe_network pull request #1918
Opened 2022-12-21 13:39 UTC by maqi

2022-12-22 06:01 UTC, joshuef requested changes
I think we're also missing a change to the `get_data_holders` functions, as they don't include elders at the moment?

2022-12-22 06:01 UTC, joshuef commented on sn_node/src/node/messaging/client_msgs.rs
> +                    .data_storage
Again, i wouldn't treat the elder as special here. If it's a holder, we request it (of ourselves)

2022-12-22 10:32 UTC, maqi commented on sn_node/src/node/data/records.rs
> +    pub(crate) async fn read_data_and_respond_to_client(
yes, I have changed the function to query self first, then the adults. hence the function name is changed.

2022-12-22 10:32 UTC, maqi commented on sn_node/src/node/messaging/client_msgs.rs
> +                info!("Try to store the data {:?} in elder locally", data.name());
This is for `storing` flow ?

2022-12-22 10:35 UTC, maqi commented on sn_node/src/node/messaging/client_msgs.rs
> +                    .data_storage
You mean treat self as an adult ?
that will make existing flow become tricky and un-necessary for some part.
such as the `record storage level` , `correlation id`, `fit into the specific message type between Adult and Elder` , etc.

2022-12-22 10:40 UTC, maqi commented
> I think we're also missing a change to the `get_data_holders` functions, as they don't include elders at the moment?

I think we don't need to do so, as the elder can check its local storage directly.
In case it doesn't have, with high chance other elders won't have either, hence can contact adults directly.
Even other elders have the copy, the client shall contact them directly already, hence no need for this elder to query other elders.

2022-12-26 11:25 UTC, maqi commented
PR updated to make elder storing data as normal adults

2022-12-28 13:16 UTC, maqi commented
work included by the PR https://github.com/maidsafe/safe_network/pull/1926

2022-12-28 13:16 UTC, closed without merging