Make elders also store data
maidsafe/safe_network pull request #1926
Opened 2022-12-26 17:49 UTC by oetyng

2022-12-26 21:59 UTC, oetyng commented
bors try

2022-12-27 09:28 UTC, joshuef requested changes
Still got a couple more commits to check, but so we have the comments thus far...

2022-12-27 09:28 UTC, joshuef commented on sn_node/src/node/data/records.rs
> +        if !is_full && data_batch_is_empty {
I know this isn't coming from this PR. But I think actually we'll never get back an empty data batch. The flow of "get missing data" returns early if there's nothing to send. 

So I think we can just remove this logic? (Unless we need that msg for some reason I'm missing? in which case we should update the flow there to ensure it's sent)

2022-12-27 09:28 UTC, joshuef commented on sn_node/src/node/data/records.rs
> +        // since we already checked our local storage above, we do not need to retain ourselves in the list of targets
I think this breaks the `nth` node checking. As the queried elder may be that `nth` node. But we'll never know if it is or if the data is on the next node.

I think we should probably move this data storage query down around line 305, so if we are nth node, we check our storage (and skip the node msg roundtrip).

2022-12-27 09:51 UTC, oetyng commented on sn_node/src/node/data/records.rs
> +        if !is_full && data_batch_is_empty {
I think it's a good fail safe, that doesn't rely on code in other places (decouples it). These are the conditions for which it will keep sending the query. It's somewhat documenting as well.

2022-12-27 09:52 UTC, oetyng commented on sn_node/src/node/data/records.rs
> +        // since we already checked our local storage above, we do not need to retain ourselves in the list of targets
There was a retain done in a previous commit, where we excluded the elder, and that broke the nth node checking.
But then the retain part was removed, and I think the nth node checking no longer breaks with that.

2022-12-27 09:56 UTC, oetyng commented on sn_node/src/node/data/records.rs
> +        // since we already checked our local storage above, we do not need to retain ourselves in the list of targets
Yeah, I can see that this comment was made on the previous commit, where the logic changed in subsequent commit,

2022-12-27 09:58 UTC, oetyng commented on sn_node/src/node/data/records.rs
> +                Ok(()) => info!("End of message flow."),
This was also made on a previous commit.
The line is no longer there.

2022-12-27 09:59 UTC, oetyng commented on sn_node/src/node/data/records.rs
> +        if !is_full && data_batch_is_empty {
Btw, there was naming bug (not logic bug though) at that specific commit, as the negation operator was used at the assignment. So what we are checking for is `!data_batch_is_empty`. But I accidently named it so that it seems we are checking for it being empty.

2022-12-27 20:31 UTC, oetyng commented
bors try

2022-12-27 20:39 UTC, oetyng commented
bors try-

2022-12-28 09:37 UTC, maqi commented on sn_node/src/node/mod.rs
> +            // when we split, the range of data that nodes are responsible for is halved,
not exactly. The network is discreted on xorname. 
Hence the `data` will cling to the node and stay within the same sub-section.
i.e. in most chance, data won't be `halved` but `stay same` in the holder.

2022-12-28 10:44 UTC, oetyng commented on sn_node/src/node/mod.rs
> +            // when we split, the range of data that nodes are responsible for is halved,
Ah, you're right.

1st section is responsible for the entire xor-range.
All the nodes together hold all data that is uploaded.

But, the nodes are (supposedly) uniformly distributed, and we have (on avg) equal number on either side of the mid point in the range. 

So, the data is already located in what will later be the child sections.

No data from a future sibling section is held by nodes.

2022-12-28 10:45 UTC, oetyng commented on sn_node/src/node/mod.rs
> +            // when we split, the range of data that nodes are responsible for is halved,
This has implications for the design and the assumptions.

Will be back later to continue this.

2022-12-28 15:45 UTC, oetyng commented on sn_node/src/node/mod.rs
> +            // when we split, the range of data that nodes are responsible for is halved,
Okay, all good as is. The wider assumptions still hold, as we are adding nodes to actually split, and thereby we get the decrease in used space.

Will remove/change the comment accordingly.

2022-12-28 17:11 UTC, maqi commented on sn_node/src/node/messaging/node_msgs.rs
> +                    let nodes = BTreeSet::from([node_id.into()]);
I am not sure, but in case a node can store data due to full, we cann't just simply kick it out?
this will just make the network overall storage situation worse?

2022-12-28 17:30 UTC, oetyng commented on sn_node/src/node/messaging/node_msgs.rs
> +                    let nodes = BTreeSet::from([node_id.into()]);
Hmm. yeah. Should it be just logging node issue here?

I can see that Josh has added a comment like this in a working branch, over the offline proposal:

```
// TODO: Ideally we should only boot it when it's been failing to fulfill
// data... this gives more nodes a chance to step in (once we have preloading)
```

2022-12-28 18:11 UTC, oetyng commented on sn_node/src/node/messaging/node_msgs.rs
> +                    let nodes = BTreeSet::from([node_id.into()]);
Yeah, I replaced that with only logging the issue.
I'm guessing that in the end, the same problem is there. We're removing a node when it's full. We're just adding a few more steps in between.

So, it isn't really a solution to the problem you describe.

But, if we were to primarily act by taking in new nodes when a node reports full (and Elders accumulate that)... then we would avoid that specific problem I think.

I think that perhaps the risk of the reporting to be abused is low.. but that depends on how the joining is designed.
If the joining is designed to pick a replacement in the same sub-range as the lost node, and accept >1 node... then this could be used to gain dominance in the section, by replacing 1 node that you own, with > 1 node that you own (given that you have control over the queue as well).

2022-12-29 06:55 UTC, joshuef approved these changes
bors r+

2022-12-29 08:06 UTC, oetyng commented on sn_interface/src/messaging/serialisation/wire_msg.rs
> +        let msg = NodeMsg::HandoverAE(100);
The test uses an arbitrary msg to test deserialization.
For the value, that is just an old habit to put non-default values, i.e. for this type non-zero values, when checking successful deserialization and similar.

2022-12-29 08:19 UTC, oetyng commented
bors try

2022-12-29 08:33 UTC, oetyng commented
bors try-

2022-12-29 08:33 UTC, oetyng commented
bors r+

2022-12-29 10:05 UTC, merged