refactor(node): pass NodeContext within UpdateNetworkAndHandleValidClientMsg
maidsafe/safe_network pull request #1986
Opened 2023-01-16 12:50 UTC by bochaco

This also checks if the network knowledge provided in a `SpentbookCmd::Spend` cmd has any update against the `NodeContext`, before trying to update the actual node's network knowledge by triggering the internal `Cmd::UpdateNetworkAndHandleValidClientMsg`.

2023-01-17 05:07 UTC, joshuef requested changes

2023-01-17 05:07 UTC, joshuef commented on sn_node/src/node/messaging/client_msgs.rs
> +                    let there_was_an_update = context.network_knowledge.update_knowledge_if_valid(
we're reusing the `context` below, but we've modified it here. 

It looks like in the update+handle func we don't need the changed info atm, but our context is not what we started with. I think it's cleaner to do a context clone and run `update_knowledge_if_valid` on _that_ so our context remains unchanged as we pass it on. (that way there's no confusion down the line on the node state vs that in the context)

2023-01-17 05:08 UTC, joshuef commented on sn_node/src/node/messaging/client_msgs.rs
> +                    let there_was_an_update = context.network_knowledge.update_knowledge_if_valid(
```suggestion
                    let there_was_an_update = context.clone().network_knowledge.update_knowledge_if_valid(
```

2023-01-17 05:09 UTC, joshuef commented on sn_node/src/node/messaging/client_msgs.rs
> +                    let there_was_an_update = context.network_knowledge.update_knowledge_if_valid(
the `mut` above on context probs needs remove there too.

2023-01-17 13:24 UTC, bochaco commented on sn_node/src/node/messaging/client_msgs.rs
> +                    let there_was_an_update = context.network_knowledge.update_knowledge_if_valid(
I think we actually want the context changed, the msg being handled carries an update for our node which is meant to be required to properly process the msg, so wee need to update our node's network knowledge to the process it, therefore if we didn't have the context we would be update the node's state and then process the msg atop the new state. Alternatively if we cloned the context to check if there is an update, we would want to get a new context instance out of the node's state after we apply the update. The context and node's state is being updated as part o the msg handling process, so I don't think it matters what was the initial state/context but what the handling process should be work on.....?

2023-01-17 16:04 UTC, joshuef approved these changes
bors r+

2023-01-18 08:08 UTC, joshuef commented
bors r+

2023-01-18 08:19 UTC, joshuef commented
bors r+

2023-01-18 10:07 UTC, merged