fix(fault): ensure std dev cannot be rounded down.
maidsafe/safe_network pull request #1987
Opened 2023-01-17 06:06 UTC by joshuef

2023-01-17 06:07 UTC, joshuef commented
bors try

2023-01-17 10:06 UTC, joshuef commented
bors try

2023-01-17 10:37 UTC, joshuef commented
bors try

2023-01-17 10:37 UTC, joshuef commented
bors try-

2023-01-17 11:25 UTC, joshuef commented
bors try

2023-01-17 11:38 UTC, maqi commented on sn_fault_detection/src/detection.rs
> +                    // track faults of all_nodes as allare elders in this situation
as allare elders ?

2023-01-17 11:38 UTC, maqi commented on sn_fault_detection/src/lib.rs
> +    /// All elders in the section (we distinguish between elders and all other nodes as their roles mean elders may have relatively higher fault levels during normal operation)
separate this long line into two short lines?

2023-01-17 11:38 UTC, maqi commented on sn_fault_detection/src/lib.rs
> +    /// Update the nodes that fault detection tracks as elders
Set the fault detection to track the input elders ?

2023-01-17 11:40 UTC, oetyng requested changes
Mostly unimportant nits, but I think the members => adults require a change?

2023-01-17 11:40 UTC, oetyng commented on sn_fault_detection/src/detection.rs
> +    /// The vec is ordered from fauliest to least faulty (returning faulty elders first)
```suggestion
    /// The vec is ordered from most to least faulty (returning faulty elders first)
```

2023-01-17 11:40 UTC, oetyng commented on sn_fault_detection/src/detection.rs
>          /// we then check that we can reliably detect those nodes
I'm tossing this sentence around in my head. I wonder if this below is what is more or less what is meant (and is it more clear?):

```
/// Test to check that when we have normal startup msgs, bad nodes have the expected issue count, and we can reliably detect those nodes.
```

2023-01-17 11:40 UTC, oetyng commented on sn_fault_detection/src/detection.rs
> +                    // track faults of all_nodes as allare elders in this situation
```suggestion
                    // track faults of all_nodes as all are elders in this situation
```

2023-01-17 11:40 UTC, oetyng commented on sn_fault_detection/src/detection.rs
> +        // we're not testin elders vs ndoes here
```suggestion
        // we're not testing elders vs nodes here
```

2023-01-17 11:40 UTC, oetyng commented on sn_fault_detection/src/detection.rs
> +                // we're not testing elders vs members here
Was thinking that this would be consistent with below comment, and so no risk to start wonder if something else is meant here?

```suggestion
                // we're not testing elders vs nodes here
```

2023-01-17 11:40 UTC, oetyng commented on sn_node/src/node/flow_ctrl/mod.rs
> +            .members()
I think this is supposed to be `adults` instead of `members`? The param in the `new` fn says `non_elder_nodes`, and members would include elders if I'm not mistaken?

(Yeah, further down `fault_detection_retain_only` takes adults.)

2023-01-17 11:47 UTC, joshuef commented on sn_fault_detection/src/detection.rs
> +        // we're working in integers here, lets not have a std dev of less than one as that's not useful
Aye, I had that differently earlier. I think we can just drop the ceil and comment here and we're fine 👍

2023-01-17 12:04 UTC, oetyng approved these changes

2023-01-17 12:10 UTC, joshuef commented
bors r+

2023-01-17 12:21 UTC, grumbach commented on sn_fault_detection/src/detection.rs
> +static STD_DEVS_AWAY: f32 = 1.5;
This is probably baseless but wouldn't `2` be a good number here? I often read stuff about 2 std dev of mean, but never seen 1.5 before. This would also help us keep it `usize`

2023-01-17 13:24 UTC, joshuef commented on sn_fault_detection/src/detection.rs
> +static STD_DEVS_AWAY: f32 = 1.5;
I have some follow up I'd like to do here. So I'll poke at this in that pr

2023-01-17 22:18 UTC, joshuef commented
bors try

2023-01-18 05:34 UTC, joshuef commented
bors r+

2023-01-18 06:31 UTC, joshuef commented
bors r+

2023-01-18 07:26 UTC, joshuef commented
bors r+

2023-01-18 07:28 UTC, joshuef commented
bors r+

2023-01-18 08:15 UTC, merged