refactor: implement new qp2p version
maidsafe/safe_network pull request #1996
Opened 2023-01-19 08:21 UTC by b-zee

This introduces quite some changes to the API that hopefully simplifies
much of the internals of the node and client.

2023-01-25 15:38 UTC, b-zee commented
bors try

2023-01-26 07:39 UTC, b-zee commented
bors try

2023-01-31 15:08 UTC, b-zee commented
bors try

2023-02-01 09:52 UTC, joshuef requested changes

2023-02-01 09:52 UTC, joshuef commented on sn_comms/src/link.rs
> +                // Ok(None) => {
lets clear up this

2023-02-01 09:52 UTC, joshuef commented on sn_node/src/node/cfg/config_handler.rs
> +        // if let Some(local_addr) = self.local_addr {
more to cleanup

2023-02-01 10:21 UTC, joshuef approved these changes
bors r+

2023-02-01 11:22 UTC, merged