fix(comm): add relocating peer to `Comm`
maidsafe/safe_network pull request #2010
Opened 2023-01-20 11:27 UTC by RolandSherwin

2023-01-23 09:39 UTC, joshuef requested changes

2023-01-23 09:39 UTC, joshuef commented on sn_node/src/node/messaging/joining_nodes.rs
> +        node.write()
MIssing a note of `NODE WRITE` here

2023-01-23 09:39 UTC, joshuef commented on sn_comms/src/lib.rs
> +    pub async fn update_members(&mut self, network_knowledge: &NetworkKnowledge) {
I think we're crossing crate boundaries here. 

This is node world stuff, which members are valid and communicable.

If we need a wrapper func on comms call to do this thats fine (and something we can add tests to actually)

2023-01-23 09:39 UTC, joshuef commented on sn_interface/src/network_knowledge/section_peers.rs
> +        self.archive.values().cloned().collect()
are all archived members valid forever?? This seems like a heavy handed solution. Can we not just add the actual node in question to the comms members?

2023-01-23 09:46 UTC, RolandSherwin commented on sn_interface/src/network_knowledge/section_peers.rs
> +        self.archive.values().cloned().collect()
Ah! I was planning to add the details about this.. Any members that are older than 5 (`ELDER_CHURN_EVENTS_TO_PRUNE_ARCHIVE`) churn events are removed from the list.. 
Maybe this is too high of a number still? If so, I will make the changes to add just the node that we want..

2023-01-23 10:57 UTC, joshuef commented on sn_interface/src/network_knowledge/section_peers.rs
> +        self.archive.values().cloned().collect()
yeh if elders dont churn for a whiiile this could be a big list

2023-02-01 16:32 UTC, RolandSherwin commented
Closing due to breaking changes to relocation.

2023-02-02 06:34 UTC, closed without merging