refactor(comms): remove use of dashmap
maidsafe/safe_network pull request #2043
Opened 2023-01-28 17:25 UTC by oetyng

- This allows a lockfree access to sessions in comms.

2023-01-29 11:52 UTC, joshuef commented
> Additional thing to note is that Elders now relay responses back to client as soon as they are received. That also puts the burden on the client to sort out if they have enough responses or not.

Are we able to separate this changeset out into a separate PR please?

2023-01-30 06:10 UTC, joshuef commented
bors try

2023-01-30 06:23 UTC, joshuef requested changes
Overall I really like this approach for comms.

Some niggly bits would be nice to get sorted w/r/t some naming feeling less clear for me, and that blurry boundary. Would be good to know what you think about the passthrough idea there

2023-01-30 06:23 UTC, joshuef commented on sn_node/src/node/messaging/streams.rs
> +    pub(crate) fn send_msg_with_bi_response(
originally i made this as it's not guaranteed that we'll see _any_ response here.

I find the name change somewhat confusing. we're sending a response? are we expecting one?

2023-01-30 06:23 UTC, joshuef commented on sn_comms/src/lib.rs
> +fn send_with_bi_response(
aye this naming is still not clear to me. (I think some docs would help)

is it still basically? `send_out_bytes_to_peer_and_return_response`? but looking for something shorter? 

`send_and_return_response` perhaps? (that it's `bi` feels like an impl detail)

2023-01-30 06:23 UTC, joshuef commented on sn_comms/src/lib.rs
> +fn map_to_client_response(
This feels like we're blurring crate boundaries here.

Feels like we're wanting this to respond faster to the client on each/every response on the bidi... and so we don't have to leak the `ResponseStream` out?

(That whole func in node is also ugly, tbh).

If we're wanting to send direct to client... Then I'd say we make the client capabale of handling NodeDataResponse. Or the nodes just send out ClientDataResponse, and we punt it straight on (I'm actually looking at this just now from another angle, but it seems sensible).

The whole mapping just feels superfluous. And if we're just directly resending `WireMsg`, then we loose that and the blurred boundary?

2023-01-30 13:01 UTC, oetyng commented on sn_node/src/node/messaging/streams.rs
> +    pub(crate) fn send_msg_with_bi_response(
I changed to `send_and_return_response`.

2023-01-30 13:01 UTC, oetyng commented on sn_comms/src/lib.rs
> +fn send_with_bi_response(
I changed to `send_and_return_response`.

2023-01-31 08:22 UTC, oetyng commented
bors try

2023-02-07 11:16 UTC, b-zee commented
Looks solid to me. Partially agree with the comment from @joshuef on crate boundaries, though  in general the interface boundaries are better. The session handling seems more solid now, with a clear idea on where sessions are managed.

2023-02-07 11:16 UTC, b-zee reviewed
Looks solid to me. Partially agree with the comment from @joshuef on crate boundaries, though in general the interface boundaries are better. The session handling seems more solid now, with a clear idea on where sessions are managed.

2023-02-07 16:56 UTC, oetyng commented
> Looks solid to me. Partially agree with the comment from @joshuef on crate boundaries, though in general the interface boundaries are better. The session handling seems more solid now, with a clear idea on where sessions are managed.

Yep, the crate boundary there was very consciously crossed, because I couldn't get there easily without it. I see it as a temporary thing, seemed like an acceptable trade-off for now, which will get sorted.

2023-02-08 09:09 UTC, joshuef commented
>  I see it as a temporary thing, seemed like an acceptable trade-off for now, which will get sorted.

I think we should be able to remove that mapping altogether now we just forward messages on?

2023-02-09 13:02 UTC, b-zee commented on sn_node/src/node/messaging/streams.rs
> +            .send_and_respond_on_stream(msg_id, node_bytes, targets_len, dst_stream);
The `targets_len` should be equal to the size of the `node_bytes` BTreeMap? If so, then we can deduce the expected amount of responses from that.

2023-02-09 13:03 UTC, b-zee commented on sn_comms/src/lib.rs
> +    expected_targets: usize,
This parameter `expected_targets` should always be equal to the `len()` of `peer_bytes`?

2023-02-09 14:31 UTC, oetyng commented on sn_node/src/node/messaging/streams.rs
> +            .send_and_respond_on_stream(msg_id, node_bytes, targets_len, dst_stream);
not when we filter mapped on serialization in streams.rs

2023-02-09 14:32 UTC, oetyng commented on sn_node/src/node/messaging/streams.rs
> +                    .serialize_with_new_dst(&dst)
it's because we need to send a response to the client anyway, so can just as well filter map here, and in comms that's where same logic will be used to send the error response to client

2023-02-09 14:32 UTC, oetyng commented on sn_node/src/node/messaging/streams.rs
> +                    .serialize_with_new_dst(&dst)
i.e. there is no shorter path to send the error to client :)

2023-02-09 14:32 UTC, oetyng commented on sn_comms/src/lib.rs
> +    expected_targets: usize,
nopes, due to filter mapped on serialization in streams.rs

2023-02-09 18:10 UTC, oetyng commented
bors r+

2023-02-09 18:10 UTC, oetyng commented
bors r+

2023-02-09 19:16 UTC, merged