feat(node): push non-blocking Cmds off thread
maidsafe/safe_network pull request #2185
Opened 2023-03-09 15:00 UTC by joshuef

Moves heaps of non critical Cmds out of the blocking mut MyNode context. Allows them to run w/ latest context; only pushing a subset of Cmds into the blocking process loop

2023-03-13 08:05 UTC, b-zee commented on sn_node/src/node/flow_ctrl/mod.rs
> +    /// Process this cmd, in blocking thread of off htead where possible
```suggestion
    /// Process this cmd, in blocking thread or off-thread where possible
```

2023-03-13 08:38 UTC, b-zee requested changes

2023-03-13 08:38 UTC, b-zee commented on sn_node/src/node/flow_ctrl/dispatcher.rs
> +        }
Not sure if this is a good suggestion, but I like returning early and reducing the indentation a level if possible (cognitive load). Rust doesn't seem particularly fit for this though. Do with it what you want.

```suggestion
        // check if we can join the dst section
        let proof = match &self.relocation_state {
            Some(RelocationState::ReadyToJoinNewSection(proof)) => proof,
            _ => return None,
        }
        
        let prev_name = proof.previous_name();
        let new_name = proof.new_name();
        if !self.network_knowledge.is_section_member(&new_name) {
            info!("Periodic check: sending request to join the section as a relocated node");
            Some(MyNode::send_to_elders_await_responses(
                self.context(),
                NodeMsg::TryJoin(Some(proof.clone())),
            ))
        } else {
            info!(
                    "{} for previous node: {:?} of age: {:?}: The new name is: {:?}, and new age is: {:?} (and pass in context age: {:?})",
                    LogMarker::RelocateEnd,
                    prev_name,
                    proof.previous_age(),
                    new_name,
                    proof.new_age(),
                    self.info().age()
                );
            info!("We've joined a section, dropping the relocation proof.");
            self.relocation_state = None;
            None
        }
```

2023-03-13 15:18 UTC, oetyng submitted a review, later dismissed
Nice to get blocking / non blocking separated!

2023-03-14 09:23 UTC, oetyng approved these changes

2023-03-14 09:33 UTC, merged