VersionHash replacing the u64 versions
maidsafe/safe_network pull request #259
Opened 2021-07-30 16:55 UTC by grumbach

Update versions with VersionHash instead of u64
VersionHash is needed by the new NRS and file containers in `sn_api`

2021-07-30 17:29 UTC, bochaco requested changes
It looks good to me, I left only a couple of minor things.

2021-07-30 17:29 UTC, bochaco commented on src/url/version_hash.rs
> +    register_entry_hash: EntryHash,
Perhaps make this generic and not necessarily for a `Register` entry, e.g. `entry_hash`, I hope eventually we have other native content types which work also with hashes and we can use `VersionHash` in the URLs in the same way.

2021-07-30 17:29 UTC, bochaco commented on src/url/mod.rs
> -        let xorurl = "safe://my.sub.hnyydyiixsfrqix9aoqg97jebuzc6748uc8rykhdd5hjrtg5o4xso9jmggbqh/path/my%20dir/my%20file.txt?this=that&this=other&color=blue&v=5&name=John+Doe#somefragment";
Perhaps use some default/random hash rather than removing it from the test, I believe this test as well as `test_safeurl_to_string` and `test_safeurl_validate` are aimed at making sure we are parsing/encoding/decoding all parts without missing any part, so removing the version/hash from them wouldn't be desirable?

2021-08-02 14:14 UTC, bochaco commented
@grumbach I just realised we'll need a commit marked as breaking change.

2021-08-04 14:51 UTC, bochaco approved these changes

2021-08-04 15:36 UTC, bochaco approved these changes

2021-08-05 10:05 UTC, connec approved these changes

2021-08-05 10:49 UTC, merged