Testnet logging
maidsafe/safe_network pull request #360
Opened 2021-09-02 09:19 UTC by connec

⚠️ This needs updated when https://github.com/maidsafe/sn_launch_tool/pull/83 is merged.

---

- 156d7def7 **refactor: Improve error handling in `testnet` binary**

  This now uses `eyre` for errors (and `color-eyre` for reporting) and has
  more robust handling of some error cases (e.g. it will no longer ignore
  legit errors when removing the node directory or handling non-UTF8
  `NODE_COUNT` values).

- 7bb87d354 **refactor: Update `sn_launch_tool`**

  The new version uses `tracing` for all its output, which gives us more
  consistent output.

- 612db3151 **chore: Update `sn_launch_tool`**

  This required changing how we call it.

2021-09-03 05:18 UTC, oetyng requested changes

2021-09-03 05:18 UTC, oetyng commented on Cargo.toml
> +sn_launch_tool = { git = "https://github.com/connec/sn_launch_tool", branch = "egregious-refactor" }
Just needs this updated :)

2021-09-03 09:23 UTC, connec commented on Cargo.toml
> +sn_launch_tool = { git = "https://github.com/connec/sn_launch_tool", branch = "egregious-refactor" }
Good catch 🤦

2021-09-06 14:19 UTC, oetyng approved these changes

2021-09-06 14:19 UTC, merged