feat: start using the genesis key from clients and joining nodes
maidsafe/safe_network pull request #376
Opened 2021-09-07 15:45 UTC by bochaco

2021-09-09 17:57 UTC, connec requested changes
Left a couple of small queries and suggestions.

2021-09-09 17:57 UTC, connec commented on src/client/connections/messaging.rs
> +        let genesis_key = bls::SecretKey::random().public_key();
Would we have to fix this for actual users to connect, e.g. for a public testnet?

2021-09-09 17:57 UTC, connec commented on src/node/config_handler.rs
> +            "Connection info file being created at {} but no genesis key is being set.",
Should we either:

- Take a `genesis_key` arg and error if it doesn't match what's in the file (conflicting networks?).
- Error if there's no file.
- Early `return Ok(())`.

Instead of writing a broken file? Even the last one seems fine, and doesn't need any new errors etc.

2021-09-09 17:57 UTC, connec commented on src/node/node_api/mod.rs
> +    /// Returns the network;s genesis key.
Nitpick:

```suggestion
    /// Returns the network's genesis key.
```

2021-09-09 17:57 UTC, connec commented on src/routing/core/msg_handling/join.rs
> +                return Ok(vec![self.send_direct_message(
Do we need to change this? Seems fine generally, but I'd assumed the idea is that only a broken/malicious node would try to join with and invalid age, and so the recipient should just ignore them (otherwise they can be spammed and have to do lots of signing etc. for their responses).

2021-09-09 19:00 UTC, bochaco commented on src/node/config_handler.rs
> +            "Connection info file being created at {} but no genesis key is being set.",
I was hesitating what to do here, I was thinking that perhaps we go for returning an Error, the user of this api needs to make sure it's calling this after it set the genesis key, it can even handle the error and call `set_connection_info` before retrying to call this function...?

2021-09-09 19:01 UTC, bochaco commented on src/client/connections/messaging.rs
> +        let genesis_key = bls::SecretKey::random().public_key();
oops...nice catch! I'll be taking care of this

2021-09-09 19:08 UTC, bochaco commented on src/routing/core/msg_handling/join.rs
> +                return Ok(vec![self.send_direct_message(
The issue is that we have this special thing about age with first section, so a joining node doesn't know up front if it's a first section or not, so it needs a `Retry` or any response with the current prefix so it can generate a name and age accordingly. Prevent spam attacks always come up to my head when I'm coding msg handlers, but it sounds like even we can reduce the effect by ignoring some type of msgs (which I agree we should do), there is always an easy way to spam a node, e.g. in this case I can spam it by sending JoinReqs with all valid data/content after I'm part of a section, this will be rejected only when hitting the verification in L68 further down....so....

2021-09-10 00:45 UTC, connec commented on src/routing/core/msg_handling/join.rs
> +                return Ok(vec![self.send_direct_message(
Good points! Makes sense to me.

2021-09-10 13:49 UTC, connec submitted a review, later dismissed

2021-09-10 14:34 UTC, connec approved these changes

2021-09-10 16:32 UTC, joshuef submitted a review, later dismissed

2021-09-10 20:41 UTC, connec approved these changes

2021-09-10 20:41 UTC, merged