send CmdAck for client cmd during test
maidsafe/safe_network pull request #929
Opened 2022-01-10 10:37 UTC by maqi

2022-01-10 17:10 UTC, joshuef commented on sn/src/client/connections/listeners.rs
> +                ServiceMsg::CmdAck { correlation_id } => {
I think we should use an `OperationId` here rather than `msg_id`. It should be unique per operation. (Currently it only exists for GETs, but there's no reason not ot have this for PUTs.

This _may_ be a bigger thing than this PR though.

2022-01-10 17:12 UTC, joshuef commented on sn/src/node/routing/core/msg_handling/service_msgs.rs
> +        // FIXME: define which signature/authority this message should really carry,
This should have the node's ed key I think, so we know where it came from.

2022-01-11 11:02 UTC, maqi commented on sn/src/client/connections/listeners.rs
> +                ServiceMsg::CmdAck { correlation_id } => {
Yeah, agree with to have it and have a separate PR for the refactory work.

2022-01-11 11:03 UTC, joshuef commented on sn/src/client/connections/messaging.rs
> -        tokio::time::sleep(self.standard_wait).await;
We want to fall back on this wait... Otherwise the client could be waiting forever for an `Ack` that never comes for one reason or another.

Basically, we want to keep such behaviour, but use ACKs to short-circuit it. 

So here, we'd perhaps change `standard_wait`'s default to be 1s. And if we get an ACK before that, we can continue.

2022-01-11 11:11 UTC, maqi commented on sn/src/client/connections/messaging.rs
> -        tokio::time::sleep(self.standard_wait).await;
right, will have a try

2022-01-12 11:02 UTC, joshuef commented on sn/src/node/routing/core/msg_handling/mod.rs
> +    async fn signature_to_client(&self, client_msg: &ServiceMsg) -> Result<(MsgKind, Bytes)> {
I'd say let's rename this as `ed_sign_client_message`, then if we do want BLS later, it's clearer.

i think we can drop these lines too?

```TODO: Dedupe this w/ node
    // Define which signature/authority this message shall carry.```

2022-01-12 12:04 UTC, joshuef approved these changes

2022-01-12 12:04 UTC, joshuef commented
bors r+

2022-01-17 14:51 UTC, joshuef requested changes

2022-01-17 14:51 UTC, joshuef commented on sn/src/client/connections/messaging.rs
> +        tokio::time::sleep(Duration::from_secs(1)).await;
Why have we gone for a fied value over the backoff here?

We shouldn't need to do a fixed wait, or indeed any now as we wait until we have a properly populated SAP in our network knowledge 🤔

2022-01-17 14:51 UTC, joshuef commented on sn/src/node/routing/core/data_records/mod.rs
> +            correlation_id: MessageId::from_xor_name(correlation_id),
is the correlation id a xorname? I'm not sure this makes sense...

2022-01-17 15:03 UTC, maqi commented on sn/src/client/connections/messaging.rs
> +        tokio::time::sleep(Duration::from_secs(1)).await;
first, the previous backoff scheme here gives a sleep around 600ms. We don't have an event update notificator here for the network knowledge here, Hence we always just `sleep` here to give the chance of update. (and `wait till update` in the later on while block)

second, change to use a fixed wait just becuase with the previous scheme, the second sleep on the backoff could be much longer due to the Exponential scheme. So here the the first `fixed` sleep is just to reduce the prolonged second sleep. We could adjust the setup of the backoff scheme to achieve the same, just it needs coupld of rounds of verification on CI runs, so I put a fixed value here for a shortcut.

2022-01-17 15:04 UTC, maqi commented on sn/src/node/routing/core/data_records/mod.rs
> +            correlation_id: MessageId::from_xor_name(correlation_id),
seems a misuse due to the rebase. 
will have a double check

2022-01-17 15:09 UTC, maqi commented on sn/src/client/connections/messaging.rs
> +    let _ = tokio::spawn(async move {
The return of the spawned stuff was `Ok(())` perviously, i.e. actually nothing meaningful to be handled.

I notice the blocking of this `send_message` being problematic becuase it only returns when completes all the sending operations (each operation contains part of establish/verify connection to peer). which hinders the listening thread to handle the response from peers. Especially in the case one of the peer having issue with the connection, which will block the whole for 1 min and make other valid responses becomes invalid.

2022-01-17 15:23 UTC, maqi commented on sn/src/node/routing/core/data_records/mod.rs
> +            correlation_id: MessageId::from_xor_name(correlation_id),
https://github.com/maidsafe/safe_network/pull/929/files#diff-9fa5f0c9092474a17ab125854b74eacd5cc3732983736f5daf93eeca32917e15R95
it's the name of the address, which is a XorName.

It shall use a proper OperationId instead though, however as I mentioned in another comment, I'd prefer to have a separate PR to tackle all OperationId related refactory, as it now need to cover both the Put and Get flow, and certain places and tests need to be care for.

2022-01-17 16:37 UTC, joshuef commented on sn/src/client/connections/messaging.rs
> +        tokio::time::sleep(Duration::from_secs(1)).await;
okay makes sense. Let's at least get this wait as a const there 👍

2022-01-17 16:39 UTC, joshuef commented on sn/src/node/routing/core/data_records/mod.rs
> +            correlation_id: MessageId::from_xor_name(correlation_id),
Hmm, that link isn't clear for me at all.

Are you saying that originaly this `correlation_id` is a xorname? If so, ;ets just change the naming of that so it makes sense. (`correlation_id` implies related `msg_id` to me)

2022-01-17 16:40 UTC, joshuef commented on sn/src/client/connections/messaging.rs
> +    let _ = tokio::spawn(async move {
>  i.e. actually nothing meaningful to be handled
Aye, but `let _ = `means even if it were changed to be meaningfu we wont see it. So we shoud not use it and instead name the variable and just let it drop (manually if needs).

----- 

w/r/t blocking: okay, good to know!

2022-01-17 17:24 UTC, bochaco commented on sn/src/client/connections/mod.rs
> +    #[allow(dead_code)]
If this is dead code, then perhaps we should just remove it? otherwise fix clippy?

2022-01-17 17:25 UTC, bochaco commented on sn/src/messaging/msg_id.rs
> +    ///
We are missing the comment here

2022-01-17 17:25 UTC, bochaco commented on sn/src/messaging/system/node_msgs.rs
> +        ///
We are missing the comment here

2022-01-17 17:34 UTC, bochaco commented on sn/src/client/connections/listeners.rs
> +    #[allow(clippy::redundant_clone)]
Can't we fix this?

2022-01-18 08:22 UTC, maqi commented on sn/src/node/routing/core/data_records/mod.rs
> +            correlation_id: MessageId::from_xor_name(correlation_id),
>Are you saying that originaly this correlation_id is a xorname?

Yes

> let's just change the naming of that so it makes sense.

ok

2022-01-18 08:28 UTC, maqi commented on sn/src/client/connections/mod.rs
> +    #[allow(dead_code)]
not sure.
I thought it might be used for the notification to the higher layer later on.

2022-01-18 11:44 UTC, joshuef approved these changes

2022-01-18 11:44 UTC, joshuef commented
bors r+

2022-01-24 09:50 UTC, maqi commented
bors

2022-01-24 09:51 UTC, maqi commented
bors r+

2022-01-24 11:00 UTC, merged