Fixing ci failures
maidsafe/safe_network pull request #971
Opened 2022-01-24 17:36 UTC by maqi

2022-01-25 09:11 UTC, joshuef requested changes

2022-01-25 09:11 UTC, joshuef commented on resources/scripts/all_nodes_joined.sh
> -nodes_joined=$(rg "ReceivedJoinApproval" "$log_dir" -g "*.log*"  -u -c | wc -l)
@maqi this line is using a `LogMarker`, so would be good to keep that in place. If we want to target another one, that's fine and we can add one in the right place for this

2022-01-25 09:15 UTC, maqi commented on resources/scripts/all_nodes_joined.sh
> -nodes_joined=$(rg "ReceivedJoinApproval" "$log_dir" -g "*.log*"  -u -c | wc -l)
'ReceivedJoinApproval' is on Trace level, however the E2E full test starting nodes with log level of Info, which doesn't have it logged at all.
Hence I choosed another one that is logged as Info already.
I can change the place of 'ReceivedJoinApproval' to be on Info level, if you think that's better?

2022-01-25 09:20 UTC, joshuef commented on resources/scripts/all_nodes_joined.sh
> -nodes_joined=$(rg "ReceivedJoinApproval" "$log_dir" -g "*.log*"  -u -c | wc -l)
Yeh, I think so. 

But we should also have the nodes logging trace level I think. I don't think that's been intentionally disabled 🤔

2022-01-25 09:26 UTC, maqi commented on resources/scripts/all_nodes_joined.sh
> -nodes_joined=$(rg "ReceivedJoinApproval" "$log_dir" -g "*.log*"  -u -c | wc -l)
I thought it's for reduce the logs size uploaded to the github?
There are 33 nodes, log with Info could save over 98% space & upload/download time

2022-01-25 11:53 UTC, joshuef approved these changes

2022-01-25 11:53 UTC, joshuef commented
bors r+

2022-01-25 15:10 UTC, maqi commented
bors r+

2022-01-25 15:33 UTC, joshuef approved these changes

2022-01-26 09:00 UTC, joshuef commented
bors r+

2022-01-26 13:34 UTC, merged