WIP: Fix interrupted join loop
maidsafe/safe_network pull request #98
Opened 2021-06-28 07:27 UTC by lionel1704

- fix(comm): properly close temp endpoint created for is_reachable() test
- refactor(main): refactor main function to use `tokio::main` and it's default runtime options

2021-06-28 10:58 UTC, maqi approved these changes

2021-06-28 14:35 UTC, joshuef requested changes

2021-06-28 14:35 UTC, joshuef commented on Cargo.toml
> -version = "0.2.20"
i dont think we should be changing this here. might break the realease/bump flow

2021-06-28 14:45 UTC, Yoga07 commented on Cargo.toml
> -version = "0.2.20"
Hmm, that wasn't intentional 🤔 Seems IDE does that or cargo.

2021-06-28 14:46 UTC, lionel1704 commented on Cargo.toml
> -version = "0.2.20"
Yea I just made the change to see if `Cargo.toml` update will not use the cache. Blind attempt 😬

2021-06-29 07:09 UTC, oetyng approved these changes

2021-06-29 07:09 UTC, merged